DROP POLICY "ingredients_select_public" ON "ingredients" CASCADE;--> statement-breakpoint
DROP POLICY "ingredients_write_role" ON "ingredients" CASCADE;--> statement-breakpoint
DROP POLICY "products_select_public" ON "products" CASCADE;--> statement-breakpoint
DROP POLICY "products_write_role" ON "products" CASCADE;--> statement-breakpoint
CREATE POLICY "ingredients_select_visible" ON "ingredients" AS PERMISSIVE FOR SELECT TO "app_runtime" USING (moderation_status = 'visible' OR (SELECT auth.role()) = 'admin');--> statement-breakpoint
CREATE POLICY "ingredients_insert_self" ON "ingredients" AS PERMISSIVE FOR INSERT TO "app_runtime" WITH CHECK ("ingredients"."created_by" = (SELECT auth.uid()) AND moderation_status = 'visible' AND (catalog_quality = 'unverified' OR (SELECT auth.role()) IN ('admin', 'contributor')));--> statement-breakpoint
CREATE POLICY "ingredients_update_owner_or_role" ON "ingredients" AS PERMISSIVE FOR UPDATE TO "app_runtime" USING ((SELECT auth.role()) IN ('admin', 'contributor') OR ("ingredients"."created_by" = (SELECT auth.uid()) AND catalog_quality = 'unverified' AND moderation_status = 'visible')) WITH CHECK ((SELECT auth.role()) IN ('admin', 'contributor') OR ("ingredients"."created_by" = (SELECT auth.uid()) AND catalog_quality = 'unverified' AND moderation_status = 'visible'));--> statement-breakpoint
CREATE POLICY "ingredients_delete_admin" ON "ingredients" AS PERMISSIVE FOR DELETE TO "app_runtime" USING ((SELECT auth.role()) = 'admin');--> statement-breakpoint
CREATE POLICY "products_select_visible" ON "products" AS PERMISSIVE FOR SELECT TO "app_runtime" USING (moderation_status = 'visible' OR (SELECT auth.role()) = 'admin');--> statement-breakpoint
CREATE POLICY "products_insert_self" ON "products" AS PERMISSIVE FOR INSERT TO "app_runtime" WITH CHECK ("products"."created_by" = (SELECT auth.uid()) AND moderation_status = 'visible' AND (catalog_quality = 'unverified' OR (SELECT auth.role()) IN ('admin', 'contributor')));--> statement-breakpoint
CREATE POLICY "products_update_owner_or_role" ON "products" AS PERMISSIVE FOR UPDATE TO "app_runtime" USING ((SELECT auth.role()) IN ('admin', 'contributor') OR ("products"."created_by" = (SELECT auth.uid()) AND catalog_quality = 'unverified' AND moderation_status = 'visible')) WITH CHECK ((SELECT auth.role()) IN ('admin', 'contributor') OR ("products"."created_by" = (SELECT auth.uid()) AND catalog_quality = 'unverified' AND moderation_status = 'visible'));--> statement-breakpoint
CREATE POLICY "products_delete_admin" ON "products" AS PERMISSIVE FOR DELETE TO "app_runtime" USING ((SELECT auth.role()) = 'admin');