import { buildTagTaxonomy } from '../../tags/tag-taxonomy-builder'
import { SUPPLEMENT_PRODUCT_TAG_SLUGS, type SupplementProductTagSlug } from './tag-slugs'

export const SUPPLEMENT_PRODUCT_TAG_CATEGORIES = [
  'goal',
  'moment',
  'restriction',
  'product_type',
  'product_label',
] as const

export type SupplementProductTagCategory = (typeof SUPPLEMENT_PRODUCT_TAG_CATEGORIES)[number]

const SUPPLEMENT_PRODUCT_TAG_LABELS: Record<SupplementProductTagSlug, string> = {
  // Goals
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.SOMMEIL]: 'Sommeil',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.ENERGIE]: 'Énergie',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.COGNITION]: 'Cognition',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.IMMUNITE]: 'Immunité',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.PEAU_CHEVEUX_ONGLES]: 'Peau, cheveux, ongles',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.DIGESTION]: 'Digestion',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.STRESS_ANXIETE]: 'Stress & anxiété',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.RECUPERATION_MUSCULAIRE]: 'Récupération musculaire',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.LONGEVITE]: 'Longévité',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.HORMONAL]: 'Équilibre hormonal',

  // Moment
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.MATIN_SUPPLEMENT]: 'Matin',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.SOIR_SUPPLEMENT]: 'Soir',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.AVEC_REPAS]: 'Avec repas',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.A_JEUN]: 'À jeun',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.AUTOUR_SPORT]: 'Autour du sport',

  // Restriction
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.GROSSESSE_INCOMPATIBLE]: 'Contre-indiqué grossesse',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.ALLAITEMENT_INCOMPATIBLE]: 'Contre-indiqué allaitement',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.INTERACTION_ANTICOAGULANTS]: 'Interaction anticoagulants',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.INTERACTION_THYROIDE]: 'Interaction thyroïde',

  // Product types
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.GELULE]: 'Gélule',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.CAPSULE]: 'Capsule',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.COMPRIME]: 'Comprimé',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.AMPOULE_BUVABLE]: 'Ampoule buvable',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.POUDRE]: 'Poudre',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.SIROP]: 'Sirop',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.GUMMY]: 'Gummy',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.HUILE_ORALE]: 'Huile orale',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.SPRAY_SUBLINGUAL]: 'Spray sublingual',

  // Product labels
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.SANS_GLUTEN]: 'Sans gluten',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.SANS_LACTOSE]: 'Sans lactose',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.BIO]: 'Bio',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.FABRICATION_FR]: 'Fabrication française',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.EXTRAIT_TITRE]: 'Extrait titré',
  [SUPPLEMENT_PRODUCT_TAG_SLUGS.DOSE_CLINIQUE]: 'Dose clinique',
}

const GOAL: SupplementProductTagSlug[] = [
  SUPPLEMENT_PRODUCT_TAG_SLUGS.SOMMEIL,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.ENERGIE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.COGNITION,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.IMMUNITE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.PEAU_CHEVEUX_ONGLES,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.DIGESTION,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.STRESS_ANXIETE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.RECUPERATION_MUSCULAIRE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.LONGEVITE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.HORMONAL,
]

const MOMENT: SupplementProductTagSlug[] = [
  SUPPLEMENT_PRODUCT_TAG_SLUGS.MATIN_SUPPLEMENT,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.SOIR_SUPPLEMENT,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.AVEC_REPAS,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.A_JEUN,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.AUTOUR_SPORT,
]

const RESTRICTION: SupplementProductTagSlug[] = [
  SUPPLEMENT_PRODUCT_TAG_SLUGS.GROSSESSE_INCOMPATIBLE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.ALLAITEMENT_INCOMPATIBLE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.INTERACTION_ANTICOAGULANTS,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.INTERACTION_THYROIDE,
]

const PRODUCT_TYPE: SupplementProductTagSlug[] = [
  SUPPLEMENT_PRODUCT_TAG_SLUGS.GELULE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.CAPSULE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.COMPRIME,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.AMPOULE_BUVABLE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.POUDRE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.SIROP,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.GUMMY,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.HUILE_ORALE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.SPRAY_SUBLINGUAL,
]

const PRODUCT_LABEL: SupplementProductTagSlug[] = [
  SUPPLEMENT_PRODUCT_TAG_SLUGS.SANS_GLUTEN,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.SANS_LACTOSE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.BIO,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.FABRICATION_FR,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.EXTRAIT_TITRE,
  SUPPLEMENT_PRODUCT_TAG_SLUGS.DOSE_CLINIQUE,
]

export const SUPPLEMENT_PRODUCT_TAG_TAXONOMY = buildTagTaxonomy<
  SupplementProductTagSlug,
  SupplementProductTagCategory
>(SUPPLEMENT_PRODUCT_TAG_LABELS, {
  goal: GOAL,
  moment: MOMENT,
  restriction: RESTRICTION,
  product_type: PRODUCT_TYPE,
  product_label: PRODUCT_LABEL,
})
