import { SKINCARE_INGREDIENT_TAG_SLUGS, type SkincareIngredientTagSlug } from './tag-slugs'

export const SKINCARE_INGREDIENT_TAG_CATEGORIES = [
  'concern',
  'skin_type',
  'ingredient_attribute',
  'skin_effect',
  'shared_label',
] as const

export type SkincareIngredientTagCategory = (typeof SKINCARE_INGREDIENT_TAG_CATEGORIES)[number]

export interface SkincareIngredientTagMeta {
  category: SkincareIngredientTagCategory
}

const CONCERN: SkincareIngredientTagSlug[] = [
  SKINCARE_INGREDIENT_TAG_SLUGS.ANTI_ROUGEURS,
  SKINCARE_INGREDIENT_TAG_SLUGS.ROSACEE,
  SKINCARE_INGREDIENT_TAG_SLUGS.COUPEROSE,
  SKINCARE_INGREDIENT_TAG_SLUGS.FLUSHS,
  SKINCARE_INGREDIENT_TAG_SLUGS.BARRIERE_CUTANEE,
  SKINCARE_INGREDIENT_TAG_SLUGS.ANTI_TACHES,
  SKINCARE_INGREDIENT_TAG_SLUGS.ANTI_ACNE,
  SKINCARE_INGREDIENT_TAG_SLUGS.ANTI_AGE,
  SKINCARE_INGREDIENT_TAG_SLUGS.HYPERPIGMENTATION,
  SKINCARE_INGREDIENT_TAG_SLUGS.DESHYDRATATION,
  SKINCARE_INGREDIENT_TAG_SLUGS.PORES_DILATES,
  SKINCARE_INGREDIENT_TAG_SLUGS.CERNES_POCHES,
  SKINCARE_INGREDIENT_TAG_SLUGS.BRILLANCE,
  SKINCARE_INGREDIENT_TAG_SLUGS.ECLAT,
  SKINCARE_INGREDIENT_TAG_SLUGS.POST_ACNE,
  SKINCARE_INGREDIENT_TAG_SLUGS.CICATRISATION,
  SKINCARE_INGREDIENT_TAG_SLUGS.MICROBIOME,
  SKINCARE_INGREDIENT_TAG_SLUGS.PHOTO_VIEILLISSEMENT,
  SKINCARE_INGREDIENT_TAG_SLUGS.TEINT_TERNE,
  SKINCARE_INGREDIENT_TAG_SLUGS.LUMIERE_BLEUE,
  SKINCARE_INGREDIENT_TAG_SLUGS.POLLUTION,
  SKINCARE_INGREDIENT_TAG_SLUGS.ECZEMA,
  SKINCARE_INGREDIENT_TAG_SLUGS.GRAIN_PEAU,
  SKINCARE_INGREDIENT_TAG_SLUGS.KERATOSE_PILAIRE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PHOTO_PROTECTION,
  SKINCARE_INGREDIENT_TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
]

const SKIN_TYPE: SkincareIngredientTagSlug[] = [
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_SECHE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_MIXTE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_GRASSE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_REACTIVE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_SENSIBLE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_NORMALE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_ATOPIQUE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_RUGUEUSE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PEAU_TOUS_TYPES,
]

const INGREDIENT_ATTRIBUTE: SkincareIngredientTagSlug[] = [
  SKINCARE_INGREDIENT_TAG_SLUGS.ANTI_OXYDANT,
  SKINCARE_INGREDIENT_TAG_SLUGS.HUMECTANT,
  SKINCARE_INGREDIENT_TAG_SLUGS.EMOLLIENT,
  SKINCARE_INGREDIENT_TAG_SLUGS.REPARATEUR,
  SKINCARE_INGREDIENT_TAG_SLUGS.ANTISEPTIQUE,
  SKINCARE_INGREDIENT_TAG_SLUGS.KERATOLYTIQUE,
  SKINCARE_INGREDIENT_TAG_SLUGS.SEBO_REGULATEUR,
  SKINCARE_INGREDIENT_TAG_SLUGS.ASTRINGENT,
  SKINCARE_INGREDIENT_TAG_SLUGS.ANTI_BACTERIEN,
  SKINCARE_INGREDIENT_TAG_SLUGS.BIOMIMETIQUE,
  SKINCARE_INGREDIENT_TAG_SLUGS.APAISANT,
  SKINCARE_INGREDIENT_TAG_SLUGS.PREBIOTIQUE,
  SKINCARE_INGREDIENT_TAG_SLUGS.ANTI_INFLAMMATOIRE,
  SKINCARE_INGREDIENT_TAG_SLUGS.PURIFIANT,
  SKINCARE_INGREDIENT_TAG_SLUGS.FILTRE_UV,
  SKINCARE_INGREDIENT_TAG_SLUGS.FILTRES_CHIMIQUES,
  SKINCARE_INGREDIENT_TAG_SLUGS.FILTRES_MINERAUX,
  SKINCARE_INGREDIENT_TAG_SLUGS.TENSIOACTIF,
  SKINCARE_INGREDIENT_TAG_SLUGS.EXCIPIENT,
  SKINCARE_INGREDIENT_TAG_SLUGS.ACTIF,
]

const SKIN_EFFECT: SkincareIngredientTagSlug[] = [
  SKINCARE_INGREDIENT_TAG_SLUGS.OCCLUSIF,
  SKINCARE_INGREDIENT_TAG_SLUGS.REPULPANT,
  SKINCARE_INGREDIENT_TAG_SLUGS.MATIFIANT,
  SKINCARE_INGREDIENT_TAG_SLUGS.PROTECTION_CUTANEE,
]

const SHARED_LABEL: SkincareIngredientTagSlug[] = [
  SKINCARE_INGREDIENT_TAG_SLUGS.COMEDOGENE,
  SKINCARE_INGREDIENT_TAG_SLUGS.NON_COMEDOGENE,
  SKINCARE_INGREDIENT_TAG_SLUGS.GROSSESSE_COMPATIBLE,
]

type Entry = [SkincareIngredientTagSlug, SkincareIngredientTagMeta]

const entries: Entry[] = [
  ...CONCERN.map((s): Entry => [s, { category: 'concern' }]),
  ...SKIN_TYPE.map((s): Entry => [s, { category: 'skin_type' }]),
  ...INGREDIENT_ATTRIBUTE.map((s): Entry => [s, { category: 'ingredient_attribute' }]),
  ...SKIN_EFFECT.map((s): Entry => [s, { category: 'skin_effect' }]),
  ...SHARED_LABEL.map((s): Entry => [s, { category: 'shared_label' }]),
]

export const SKINCARE_INGREDIENT_TAG_TAXONOMY = Object.fromEntries(entries) as Record<
  SkincareIngredientTagSlug,
  SkincareIngredientTagMeta
>

export function getSkincareIngredientTagCategory(
  slug: SkincareIngredientTagSlug
): SkincareIngredientTagCategory | undefined {
  return SKINCARE_INGREDIENT_TAG_TAXONOMY[slug]?.category
}
