import { HAIRCARE_INGREDIENT_TAG_SLUGS, type HaircareIngredientTagSlug } from './tag-slugs'

export const HAIRCARE_INGREDIENT_TAG_CATEGORIES = [
  'concern',
  'hair_type',
  'ingredient_attribute',
  'hair_effect',
] as const

export type HaircareIngredientTagCategory = (typeof HAIRCARE_INGREDIENT_TAG_CATEGORIES)[number]

export interface HaircareIngredientTagMeta {
  category: HaircareIngredientTagCategory
}

const CONCERN: HaircareIngredientTagSlug[] = [
  HAIRCARE_INGREDIENT_TAG_SLUGS.PELLICULES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CHUTE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CASSE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.FOURCHES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.FRISOTTIS,
  HAIRCARE_INGREDIENT_TAG_SLUGS.MANQUE_VOLUME,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CHEVEUX_SECS,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CHEVEUX_GRAS,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CUIR_CHEVELU_SENSIBLE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CUIR_CHEVELU_IRRITE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.ALOPECIE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.POST_COLORATION,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CHEVEUX_TERNES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.JAUNISSEMENT_BLOND,
  HAIRCARE_INGREDIENT_TAG_SLUGS.POROSITE_EXCESSIVE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.POINTES_SECHES,
]

const HAIR_TYPE: HaircareIngredientTagSlug[] = [
  HAIRCARE_INGREDIENT_TAG_SLUGS.LISSES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.ONDULES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.BOUCLES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CREPUS,
  HAIRCARE_INGREDIENT_TAG_SLUGS.FINS,
  HAIRCARE_INGREDIENT_TAG_SLUGS.EPAIS,
  HAIRCARE_INGREDIENT_TAG_SLUGS.MOYENS,
  HAIRCARE_INGREDIENT_TAG_SLUGS.COLORES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.DECOLORES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.NATURELS,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CHEVEUX_TOUS_TYPES,
]

const INGREDIENT_ATTRIBUTE: HaircareIngredientTagSlug[] = [
  HAIRCARE_INGREDIENT_TAG_SLUGS.HUMECTANT,
  HAIRCARE_INGREDIENT_TAG_SLUGS.EMOLLIENT,
  HAIRCARE_INGREDIENT_TAG_SLUGS.PROTEINE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.FILM_PROTECTEUR,
  HAIRCARE_INGREDIENT_TAG_SLUGS.TENSIOACTIF_DOUX,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CHELATEUR,
  HAIRCARE_INGREDIENT_TAG_SLUGS.ANTI_PELLICULAIRE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.STIMULANT_FOLLICULE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.CONDITIONNEUR_CATIONIQUE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.GAINANT,
]

const HAIR_EFFECT: HaircareIngredientTagSlug[] = [
  HAIRCARE_INGREDIENT_TAG_SLUGS.BRILLANCE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.DOUCEUR,
  HAIRCARE_INGREDIENT_TAG_SLUGS.VOLUME,
  HAIRCARE_INGREDIENT_TAG_SLUGS.DISCIPLINE,
  HAIRCARE_INGREDIENT_TAG_SLUGS.HYDRATATION,
  HAIRCARE_INGREDIENT_TAG_SLUGS.NUTRITION,
  HAIRCARE_INGREDIENT_TAG_SLUGS.LISSANT,
  HAIRCARE_INGREDIENT_TAG_SLUGS.FIXATION,
  HAIRCARE_INGREDIENT_TAG_SLUGS.DEFINITION_BOUCLES,
  HAIRCARE_INGREDIENT_TAG_SLUGS.GAINAGE,
]

type Entry = [HaircareIngredientTagSlug, HaircareIngredientTagMeta]

const entries: Entry[] = [
  ...CONCERN.map((s): Entry => [s, { category: 'concern' }]),
  ...HAIR_TYPE.map((s): Entry => [s, { category: 'hair_type' }]),
  ...INGREDIENT_ATTRIBUTE.map((s): Entry => [s, { category: 'ingredient_attribute' }]),
  ...HAIR_EFFECT.map((s): Entry => [s, { category: 'hair_effect' }]),
]

export const HAIRCARE_INGREDIENT_TAG_TAXONOMY = Object.fromEntries(entries) as Record<
  HaircareIngredientTagSlug,
  HaircareIngredientTagMeta
>

export function getHaircareIngredientTagCategory(
  slug: HaircareIngredientTagSlug
): HaircareIngredientTagCategory | undefined {
  return HAIRCARE_INGREDIENT_TAG_TAXONOMY[slug]?.category
}
