import { HAIRCARE_PRODUCT_TAG_SLUGS, type HaircareProductTagSlug } from './tag-slugs'

export const HAIRCARE_PRODUCT_TAG_CATEGORIES = [
  'concern',
  'hair_type',
  'product_type',
  'routine_step',
  'hair_effect',
  'product_label',
] as const

export type HaircareProductTagCategory = (typeof HAIRCARE_PRODUCT_TAG_CATEGORIES)[number]

export interface HaircareProductTagMeta {
  category: HaircareProductTagCategory
}

const CONCERN: HaircareProductTagSlug[] = [
  HAIRCARE_PRODUCT_TAG_SLUGS.PELLICULES,
  HAIRCARE_PRODUCT_TAG_SLUGS.CHUTE,
  HAIRCARE_PRODUCT_TAG_SLUGS.CASSE,
  HAIRCARE_PRODUCT_TAG_SLUGS.FOURCHES,
  HAIRCARE_PRODUCT_TAG_SLUGS.MANQUE_VOLUME,
  HAIRCARE_PRODUCT_TAG_SLUGS.CHEVEUX_SECS,
  HAIRCARE_PRODUCT_TAG_SLUGS.CHEVEUX_GRAS,
  HAIRCARE_PRODUCT_TAG_SLUGS.RACINES_GRASSES,
  HAIRCARE_PRODUCT_TAG_SLUGS.CUIR_CHEVELU_SENSIBLE,
  HAIRCARE_PRODUCT_TAG_SLUGS.CUIR_CHEVELU_IRRITE,
  HAIRCARE_PRODUCT_TAG_SLUGS.ALOPECIE,
  HAIRCARE_PRODUCT_TAG_SLUGS.POST_COLORATION,
  HAIRCARE_PRODUCT_TAG_SLUGS.CHEVEUX_TERNES,
  HAIRCARE_PRODUCT_TAG_SLUGS.JAUNISSEMENT_BLOND,
  HAIRCARE_PRODUCT_TAG_SLUGS.POROSITE_EXCESSIVE,
  HAIRCARE_PRODUCT_TAG_SLUGS.POINTES_SECHES,
]

const HAIR_TYPE: HaircareProductTagSlug[] = [
  HAIRCARE_PRODUCT_TAG_SLUGS.LISSES,
  HAIRCARE_PRODUCT_TAG_SLUGS.ONDULES,
  HAIRCARE_PRODUCT_TAG_SLUGS.BOUCLES,
  HAIRCARE_PRODUCT_TAG_SLUGS.CREPUS,
  HAIRCARE_PRODUCT_TAG_SLUGS.FINS,
  HAIRCARE_PRODUCT_TAG_SLUGS.EPAIS,
  HAIRCARE_PRODUCT_TAG_SLUGS.MOYENS,
  HAIRCARE_PRODUCT_TAG_SLUGS.COLORES,
  HAIRCARE_PRODUCT_TAG_SLUGS.DECOLORES,
  HAIRCARE_PRODUCT_TAG_SLUGS.NATURELS,
  HAIRCARE_PRODUCT_TAG_SLUGS.CHEVEUX_TOUS_TYPES,
]

const PRODUCT_TYPE: HaircareProductTagSlug[] = [
  HAIRCARE_PRODUCT_TAG_SLUGS.SHAMPOOING,
  HAIRCARE_PRODUCT_TAG_SLUGS.SHAMPOOING_SEC,
  HAIRCARE_PRODUCT_TAG_SLUGS.SHAMPOOING_CLARIFIANT,
  HAIRCARE_PRODUCT_TAG_SLUGS.CO_WASH,
  HAIRCARE_PRODUCT_TAG_SLUGS.APRES_SHAMPOOING,
  HAIRCARE_PRODUCT_TAG_SLUGS.MASQUE_CAPILLAIRE,
  HAIRCARE_PRODUCT_TAG_SLUGS.SOIN_PROFOND,
  HAIRCARE_PRODUCT_TAG_SLUGS.SERUM_CAPILLAIRE,
  HAIRCARE_PRODUCT_TAG_SLUGS.HUILE_CAPILLAIRE,
  HAIRCARE_PRODUCT_TAG_SLUGS.LEAVE_IN,
  HAIRCARE_PRODUCT_TAG_SLUGS.LOTION_FORTIFIANTE,
  HAIRCARE_PRODUCT_TAG_SLUGS.GEL_COIFFANT,
  HAIRCARE_PRODUCT_TAG_SLUGS.MOUSSE_COIFFANTE,
  HAIRCARE_PRODUCT_TAG_SLUGS.CREME_COIFFANTE,
  HAIRCARE_PRODUCT_TAG_SLUGS.SPRAY_COIFFANT,
  HAIRCARE_PRODUCT_TAG_SLUGS.SPRAY_THERMOPROTECTEUR,
  HAIRCARE_PRODUCT_TAG_SLUGS.CIRE_COIFFANTE,
]

const ROUTINE_STEP: HaircareProductTagSlug[] = [
  HAIRCARE_PRODUCT_TAG_SLUGS.PRE_SHAMPOOING,
  HAIRCARE_PRODUCT_TAG_SLUGS.LAVAGE,
  HAIRCARE_PRODUCT_TAG_SLUGS.CONDITIONNEMENT,
  HAIRCARE_PRODUCT_TAG_SLUGS.MASQUE_HEBDO_CHEVEUX,
  HAIRCARE_PRODUCT_TAG_SLUGS.TRAITEMENT_CUIR_CHEVELU,
  HAIRCARE_PRODUCT_TAG_SLUGS.SOIN_SANS_RINCAGE,
  HAIRCARE_PRODUCT_TAG_SLUGS.COIFFAGE,
  HAIRCARE_PRODUCT_TAG_SLUGS.FINITION,
]

const HAIR_EFFECT: HaircareProductTagSlug[] = [
  HAIRCARE_PRODUCT_TAG_SLUGS.BRILLANCE,
  HAIRCARE_PRODUCT_TAG_SLUGS.DOUCEUR,
  HAIRCARE_PRODUCT_TAG_SLUGS.VOLUME,
  HAIRCARE_PRODUCT_TAG_SLUGS.DISCIPLINE,
  HAIRCARE_PRODUCT_TAG_SLUGS.HYDRATATION,
  HAIRCARE_PRODUCT_TAG_SLUGS.NUTRITION,
  HAIRCARE_PRODUCT_TAG_SLUGS.LISSANT,
  HAIRCARE_PRODUCT_TAG_SLUGS.FIXATION,
  HAIRCARE_PRODUCT_TAG_SLUGS.DEFINITION_BOUCLES,
  HAIRCARE_PRODUCT_TAG_SLUGS.GAINAGE,
  HAIRCARE_PRODUCT_TAG_SLUGS.ANTI_FRISOTTIS,
  HAIRCARE_PRODUCT_TAG_SLUGS.DEMELAGE,
  HAIRCARE_PRODUCT_TAG_SLUGS.REPARATION,
  HAIRCARE_PRODUCT_TAG_SLUGS.THERMOPROTECTION,
]

const PRODUCT_LABEL: HaircareProductTagSlug[] = [
  HAIRCARE_PRODUCT_TAG_SLUGS.SANS_SULFATES,
  HAIRCARE_PRODUCT_TAG_SLUGS.SANS_SILICONES,
  HAIRCARE_PRODUCT_TAG_SLUGS.SANS_PARFUM,
  HAIRCARE_PRODUCT_TAG_SLUGS.CGM_FRIENDLY,
  HAIRCARE_PRODUCT_TAG_SLUGS.VEGAN,
  HAIRCARE_PRODUCT_TAG_SLUGS.CRUELTY_FREE,
  HAIRCARE_PRODUCT_TAG_SLUGS.BIO_NATUREL,
  HAIRCARE_PRODUCT_TAG_SLUGS.HYPOALLERGENIQUE,
]

type Entry = [HaircareProductTagSlug, HaircareProductTagMeta]

const entries: Entry[] = [
  ...CONCERN.map((s): Entry => [s, { category: 'concern' }]),
  ...HAIR_TYPE.map((s): Entry => [s, { category: 'hair_type' }]),
  ...PRODUCT_TYPE.map((s): Entry => [s, { category: 'product_type' }]),
  ...ROUTINE_STEP.map((s): Entry => [s, { category: 'routine_step' }]),
  ...HAIR_EFFECT.map((s): Entry => [s, { category: 'hair_effect' }]),
  ...PRODUCT_LABEL.map((s): Entry => [s, { category: 'product_label' }]),
]

export const HAIRCARE_PRODUCT_TAG_TAXONOMY = Object.fromEntries(entries) as Record<
  HaircareProductTagSlug,
  HaircareProductTagMeta
>

export function getHaircareProductTagCategory(
  slug: HaircareProductTagSlug
): HaircareProductTagCategory | undefined {
  return HAIRCARE_PRODUCT_TAG_TAXONOMY[slug]?.category
}
