// Skincare Product Tag Slugs
// Tags applicable to skincare products.
// Categories: concern, skin_type, skin_zone, product_type, routine_step,
//             skin_effect, product_label, shared_label.

export const SKINCARE_PRODUCT_TAG_SLUGS = {
  // Concerns
  ANTI_ROUGEURS: 'anti-rougeurs',
  ROSACEE: 'rosacee',
  COUPEROSE: 'couperose',
  FLUSHS: 'flushs',
  BARRIERE_CUTANEE: 'barriere-cutanee',
  ANTI_TACHES: 'anti-taches',
  ANTI_ACNE: 'anti-acne',
  ANTI_AGE: 'anti-age',
  HYPERPIGMENTATION: 'hyperpigmentation',
  DESHYDRATATION: 'deshydratation',
  PORES_DILATES: 'pores-dilates',
  CERNES_POCHES: 'cernes-poches',
  BRILLANCE: 'brillance',
  ECLAT: 'eclat',
  POST_ACNE: 'post-acne',
  CICATRISATION: 'cicatrisation',
  MICROBIOME: 'microbiome',
  PHOTO_VIEILLISSEMENT: 'photo-vieillissement',
  TEINT_TERNE: 'teint-terne',
  LUMIERE_BLEUE: 'lumiere-bleue',
  POLLUTION: 'pollution',
  ECZEMA: 'eczema',
  GRAIN_PEAU: 'grain-peau',
  KERATOSE_PILAIRE: 'keratose-pilaire',
  PHOTO_PROTECTION: 'photo-protection',
  BARRIERE_CUTANEE_ALTEREE: 'barriere-cutanee-alteree',

  // Skin types
  PEAU_SECHE: 'peau-seche',
  PEAU_MIXTE: 'peau-mixte',
  PEAU_GRASSE: 'peau-grasse',
  PEAU_REACTIVE: 'peau-reactive',
  PEAU_SENSIBLE: 'peau-sensible',
  PEAU_NORMALE: 'peau-normale',
  PEAU_ATOPIQUE: 'peau-atopique',
  PEAU_RUGUEUSE: 'peau-rugueuse',
  PEAU_TOUS_TYPES: 'tous-types',

  // Skin zones
  ZONE_VISAGE: 'zone-visage',
  ZONE_CORPS: 'zone-corps',
  ZONE_YEUX: 'zone-yeux',
  ZONE_LEVRES: 'zone-levres',
  ZONE_MAINS: 'zone-mains',

  // Product types
  BAUME_DEMAQUILLANT: 'baume-demaquillant',
  HUILE_DEMAQUILLANTE: 'huile-demaquillante',
  HUILE_NETTOYANTE: 'huile-nettoyante',
  GEL_NETTOYANT: 'gel-nettoyant',
  MOUSSE_NETTOYANTE: 'mousse-nettoyante',
  LAIT_NETTOYANT: 'lait-nettoyant',
  CREME_NETTOYANTE: 'creme-nettoyante',
  EAU_MICELLAIRE: 'eau-micellaire',
  TONIQUE: 'tonique',
  ESSENCE: 'essence',
  LOTION: 'lotion',
  BRUME: 'brume',
  PRIMER: 'primer',
  SERUM: 'serum',
  AMPOULE: 'ampoule',
  HUILE_VISAGE: 'huile-visage',
  SPOT_TREATMENT: 'spot-treatment',
  CREME_HYDRATANTE: 'creme-hydratante',
  GEL_CREME: 'gel-creme',
  CREME_DE_NUIT: 'creme-de-nuit',
  BAUME: 'baume',
  SLEEPING_MASK: 'sleeping-mask',
  CONTOUR_YEUX: 'contour-yeux',
  SOIN_LEVRES: 'soin-levres',
  EXFOLIANT_CHIMIQUE: 'exfoliant-chimique',
  EXFOLIANT_PHYSIQUE: 'exfoliant-physique',
  MASQUE_ARGILE: 'masque-argile',
  MASQUE_TISSU: 'masque-tissu',
  MASQUE_HYDRATANT: 'masque-hydratant',
  CREME_SOLAIRE: 'creme-solaire',
  CREME_SOLAIRE_TEINTEE: 'creme-solaire-teintee',
  APRES_SOLEIL: 'apres-soleil',
  AUTO_BRONZANT: 'auto-bronzant',
  LAIT_CORPS: 'lait-corps',
  CREME_CORPS: 'creme-corps',
  CREME_MAINS: 'creme-mains',
  HUILE_CORPS: 'huile-corps',
  GOMMAGE_CORPS: 'gommage-corps',
  NETTOYANT_CORPS: 'nettoyant-corps',
  DEODORANT: 'deodorant',
  CREME_PIEDS: 'creme-pieds',
  PATCH: 'patch',
  OUTIL_MASSAGE: 'outil-massage',

  // Routine steps
  MATIN: 'matin',
  SOIR: 'soir',
  NETTOYANT: 'nettoyant',
  DOUBLE_NETTOYAGE_1: 'double-nettoyage-1',
  DOUBLE_NETTOYAGE_2: 'double-nettoyage-2',
  PREPARATION: 'preparation',
  TRAITEMENT: 'traitement',
  HYDRATATION: 'hydratation',
  EMOLLIENCE: 'emollience',
  PROTECTION_SOLAIRE: 'protection-solaire',
  OCCLUSION: 'occlusion',
  SOIN_YEUX: 'soin-yeux',
  SOIN_LOCALISE: 'soin-localise',
  EXFOLIATION: 'exfoliation',
  MASQUE_HEBDO: 'masque-hebdo',

  // Skin effects
  OCCLUSIF: 'occlusif',
  REPULPANT: 'repulpant',
  MATIFIANT: 'matifiant',
  PROTECTION_CUTANEE: 'protection-cutanee',
  TEXTURE_RICHE: 'texture-riche',
  TEXTURE_LEGERE: 'texture-legere',
  ANTI_OXYDANT: 'anti-oxydant',
  APAISANT: 'apaisant',
  SEBO_REGULATEUR: 'sebo-regulateur',
  REPARATEUR: 'reparateur',
  PURIFIANT: 'purifiant',
  PREBIOTIQUE: 'prebiotique',
  KERATOLYTIQUE: 'keratolytique',

  // Product labels
  SANS_PARFUM: 'sans-parfum',
  BIO_NATUREL: 'bio-naturel',
  VEGAN: 'vegan',
  CRUELTY_FREE: 'cruelty-free',
  HYPOALLERGENIQUE: 'hypoallergenique',
  PIGMENTS_VERTS: 'pigments-verts',
  SANS_SAVON: 'sans-savon',
  FILTRES_CHIMIQUES: 'filtres-chimiques',
  FILTRES_MINERAUX: 'filtres-mineraux',
  GROSSESSE_COMPATIBLE: 'grossesse-compatible',

  // Shared labels
  COMEDOGENE: 'comedogene',
  NON_COMEDOGENE: 'non-comedogene',
} as const

export type SkincareProductTagSlug =
  (typeof SKINCARE_PRODUCT_TAG_SLUGS)[keyof typeof SKINCARE_PRODUCT_TAG_SLUGS]
