import { buildTagTaxonomy } from '../tag-taxonomy-builder'
import { SKINCARE_PRODUCT_TAG_SLUGS, type SkincareProductTagSlug } from './tag-slugs'

export const SKINCARE_PRODUCT_TAG_CATEGORIES = [
  'concern',
  'skin_type',
  'skin_zone',
  'product_type_v2',
  'texture',
  'routine_step_v2',
  'routine_moment',
  'skin_effect',
  'sensation',
  'product_characteristic',
  'actif_class',
] as const

export type SkincareProductTagCategory = (typeof SKINCARE_PRODUCT_TAG_CATEGORIES)[number]

export interface SkincareProductTagMeta {
  category: SkincareProductTagCategory
  label: string
}

const SKINCARE_PRODUCT_TAG_LABELS: Record<SkincareProductTagSlug, string> = {
  // Concerns
  [SKINCARE_PRODUCT_TAG_SLUGS.ACNE_IMPERFECTIONS]: 'Acné / Imperfections',
  [SKINCARE_PRODUCT_TAG_SLUGS.ROUGEURS_VASCULAIRES]: 'Rougeurs vasculaires',
  [SKINCARE_PRODUCT_TAG_SLUGS.ECZEMA_ATOPIE]: 'Eczéma / Atopie',
  [SKINCARE_PRODUCT_TAG_SLUGS.BARRIERE_CUTANEE]: 'Barrière cutanée',
  [SKINCARE_PRODUCT_TAG_SLUGS.HYPERPIGMENTATION]: 'Hyperpigmentation',
  [SKINCARE_PRODUCT_TAG_SLUGS.REPARATION]: 'Réparation',
  [SKINCARE_PRODUCT_TAG_SLUGS.KERATOSE_PILAIRE]: 'Kératose pilaire',
  [SKINCARE_PRODUCT_TAG_SLUGS.DESHYDRATATION]: 'Déshydratation',
  [SKINCARE_PRODUCT_TAG_SLUGS.ECLAT_TEINT]: 'Éclat / Teint uniforme',
  [SKINCARE_PRODUCT_TAG_SLUGS.ANTI_AGE]: 'Anti-âge',
  [SKINCARE_PRODUCT_TAG_SLUGS.PORES_SEBUM]: 'Pores / Sébum',
  [SKINCARE_PRODUCT_TAG_SLUGS.CERNES_POCHES]: 'Cernes et poches',
  [SKINCARE_PRODUCT_TAG_SLUGS.PROTECTION]: 'Protection',

  // Skin types
  [SKINCARE_PRODUCT_TAG_SLUGS.PEAU_SECHE]: 'Peau sèche',
  [SKINCARE_PRODUCT_TAG_SLUGS.PEAU_MIXTE]: 'Peau mixte',
  [SKINCARE_PRODUCT_TAG_SLUGS.PEAU_GRASSE]: 'Peau grasse',
  [SKINCARE_PRODUCT_TAG_SLUGS.PEAU_SENSIBLE]: 'Peau sensible',
  [SKINCARE_PRODUCT_TAG_SLUGS.PEAU_NORMALE]: 'Peau normale',

  // Skin zones
  [SKINCARE_PRODUCT_TAG_SLUGS.ZONE_VISAGE]: 'Visage',
  [SKINCARE_PRODUCT_TAG_SLUGS.ZONE_CORPS]: 'Corps',
  [SKINCARE_PRODUCT_TAG_SLUGS.ZONE_YEUX]: 'Yeux',
  [SKINCARE_PRODUCT_TAG_SLUGS.ZONE_LEVRES]: 'Lèvres',
  [SKINCARE_PRODUCT_TAG_SLUGS.ZONE_MAINS]: 'Mains',
  [SKINCARE_PRODUCT_TAG_SLUGS.ZONE_PIEDS]: 'Pieds',

  // Product types V2
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_NETTOYANT]: 'Nettoyant',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_TONER]: 'Toner',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_MIST]: 'Mist / Brume',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_SERUM]: 'Sérum / Concentré',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_HYDRATANT]: 'Hydratant',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_MASQUE]: 'Masque',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_EXFOLIATION]: 'Exfoliation',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_SOLAIRE]: 'Protection solaire',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_TRAITEMENT]: 'Traitement ciblé',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_PRIMER]: 'Base de maquillage',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_DEODORANT]: 'Déodorant',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYPE_OUTIL]: 'Outil',

  // Textures
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_GEL]: 'Gel',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_CREME]: 'Crème',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_BAUME]: 'Baume',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_HUILE]: 'Huile',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_LAIT]: 'Lait',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_MOUSSE]: 'Mousse',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_EAU]: 'Eau',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_PATCH]: 'Patch',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_STICK]: 'Stick',

  // Routine steps V2
  [SKINCARE_PRODUCT_TAG_SLUGS.STEP_NETTOYAGE_1]: '1er nettoyage',
  [SKINCARE_PRODUCT_TAG_SLUGS.STEP_NETTOYAGE_2]: '2e nettoyage',
  [SKINCARE_PRODUCT_TAG_SLUGS.STEP_PREPARATION]: 'Préparation',
  [SKINCARE_PRODUCT_TAG_SLUGS.STEP_TRAITEMENT]: 'Traitement',
  [SKINCARE_PRODUCT_TAG_SLUGS.STEP_HYDRATATION]: 'Hydratation',
  [SKINCARE_PRODUCT_TAG_SLUGS.STEP_OCCLUSIF]: 'Occlusif',
  [SKINCARE_PRODUCT_TAG_SLUGS.STEP_PROTECTION_SOLAIRE]: 'Protection solaire',

  // Routine moments
  [SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_MATIN]: 'Matin',
  [SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_SOIR]: 'Soir',
  [SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_HEBDOMADAIRE]: 'Hebdomadaire',
  [SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_USAGE_LOCALISE]: 'Usage localisé',
  [SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_CRISE]: 'En cas de crise',

  // Skin effects
  [SKINCARE_PRODUCT_TAG_SLUGS.OCCLUSIF]: 'Occlusif',
  [SKINCARE_PRODUCT_TAG_SLUGS.REPULPANT]: 'Repulpant',
  [SKINCARE_PRODUCT_TAG_SLUGS.MATIFIANT]: 'Matifiant',
  [SKINCARE_PRODUCT_TAG_SLUGS.PROTECTION_CUTANEE]: 'Protection cutanée',
  [SKINCARE_PRODUCT_TAG_SLUGS.ANTI_OXYDANT]: 'Anti-oxydant',
  [SKINCARE_PRODUCT_TAG_SLUGS.APAISANT]: 'Apaisant',
  [SKINCARE_PRODUCT_TAG_SLUGS.SEBO_REGULATEUR]: 'Sébo-régulateur',
  [SKINCARE_PRODUCT_TAG_SLUGS.REPARATEUR]: 'Réparateur',
  [SKINCARE_PRODUCT_TAG_SLUGS.PURIFIANT]: 'Purifiant',
  [SKINCARE_PRODUCT_TAG_SLUGS.PREBIOTIQUE]: 'Prébiotique',
  [SKINCARE_PRODUCT_TAG_SLUGS.KERATOLYTIQUE]: 'Kératolytique',

  // Sensations
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_RICHE]: 'Texture riche',
  [SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_LEGERE]: 'Texture légère',
  [SKINCARE_PRODUCT_TAG_SLUGS.NON_GRAS]: 'Non gras',
  [SKINCARE_PRODUCT_TAG_SLUGS.FINI_MAT]: 'Fini mat',
  [SKINCARE_PRODUCT_TAG_SLUGS.FINI_GLOWY]: 'Fini glowy',
  [SKINCARE_PRODUCT_TAG_SLUGS.ABSORPTION_RAPIDE]: 'Absorption rapide',

  // Product characteristics
  [SKINCARE_PRODUCT_TAG_SLUGS.SANS_PARFUM]: 'Sans parfum',
  [SKINCARE_PRODUCT_TAG_SLUGS.SANS_SAVON]: 'Sans savon',
  [SKINCARE_PRODUCT_TAG_SLUGS.HYPOALLERGENIQUE]: 'Hypoallergénique',
  [SKINCARE_PRODUCT_TAG_SLUGS.GROSSESSE_COMPATIBLE]: 'Grossesse compatible',
  [SKINCARE_PRODUCT_TAG_SLUGS.BIO_NATUREL]: 'Bio / Naturel',
  [SKINCARE_PRODUCT_TAG_SLUGS.VEGAN]: 'Vegan',
  [SKINCARE_PRODUCT_TAG_SLUGS.CRUELTY_FREE]: 'Cruelty-free',
  [SKINCARE_PRODUCT_TAG_SLUGS.FILTRES_MINERAUX]: 'Filtres minéraux',
  [SKINCARE_PRODUCT_TAG_SLUGS.FILTRES_CHIMIQUES]: 'Filtres chimiques',
  [SKINCARE_PRODUCT_TAG_SLUGS.PIGMENTS_VERTS]: 'Pigments verts',
  [SKINCARE_PRODUCT_TAG_SLUGS.COMEDOGENE]: 'Comédogène',
  [SKINCARE_PRODUCT_TAG_SLUGS.NON_COMEDOGENE]: 'Non comédogène',

  // Actif class (pharmacological clusters)
  [SKINCARE_PRODUCT_TAG_SLUGS.RETINOIDS]: 'Rétinoïdes',
  [SKINCARE_PRODUCT_TAG_SLUGS.RETINOL_ALTERNATIVES]: 'Alternatives au rétinol',
  [SKINCARE_PRODUCT_TAG_SLUGS.VITAMIN_C]: 'Vitamine C',
  [SKINCARE_PRODUCT_TAG_SLUGS.VITAMIN_E]: 'Vitamine E',
  [SKINCARE_PRODUCT_TAG_SLUGS.NIACINAMIDE]: 'Niacinamide',
  [SKINCARE_PRODUCT_TAG_SLUGS.AHA]: 'AHA',
  [SKINCARE_PRODUCT_TAG_SLUGS.BHA]: 'BHA',
  [SKINCARE_PRODUCT_TAG_SLUGS.PHA]: 'PHA',
  [SKINCARE_PRODUCT_TAG_SLUGS.ENZYMES_EXFOLIANTS]: 'Enzymes exfoliantes',
  [SKINCARE_PRODUCT_TAG_SLUGS.CERAMIDES]: 'Céramides',
  [SKINCARE_PRODUCT_TAG_SLUGS.HYALURONIC_ACID]: 'Acide hyaluronique',
  [SKINCARE_PRODUCT_TAG_SLUGS.PEPTIDES]: 'Peptides',
  [SKINCARE_PRODUCT_TAG_SLUGS.POLYPHENOLS]: 'Polyphénols',
  [SKINCARE_PRODUCT_TAG_SLUGS.CENTELLA]: 'Centella asiatica',
  [SKINCARE_PRODUCT_TAG_SLUGS.TYROSINASE_INHIBITORS]: 'Inhibiteurs de tyrosinase',
  [SKINCARE_PRODUCT_TAG_SLUGS.AZELAIC_ACID]: 'Acide azélaïque',
}

// Concern groups are display-only — DB stores flat concern slugs.
// Frontend reads SKINCARE_PRODUCT_CONCERN_GROUPS to render two sub-sections.
export const SKINCARE_PRODUCT_CONCERN_GROUP_KEYS = ['functional', 'aesthetic'] as const
export type SkincareProductConcernGroup = (typeof SKINCARE_PRODUCT_CONCERN_GROUP_KEYS)[number]

const CONCERN_FUNCTIONAL: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.ACNE_IMPERFECTIONS,
  SKINCARE_PRODUCT_TAG_SLUGS.ROUGEURS_VASCULAIRES,
  SKINCARE_PRODUCT_TAG_SLUGS.ECZEMA_ATOPIE,
  SKINCARE_PRODUCT_TAG_SLUGS.BARRIERE_CUTANEE,
  SKINCARE_PRODUCT_TAG_SLUGS.HYPERPIGMENTATION,
  SKINCARE_PRODUCT_TAG_SLUGS.REPARATION,
  SKINCARE_PRODUCT_TAG_SLUGS.KERATOSE_PILAIRE,
  SKINCARE_PRODUCT_TAG_SLUGS.DESHYDRATATION,
]

const CONCERN_AESTHETIC: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.ECLAT_TEINT,
  SKINCARE_PRODUCT_TAG_SLUGS.ANTI_AGE,
  SKINCARE_PRODUCT_TAG_SLUGS.PORES_SEBUM,
  SKINCARE_PRODUCT_TAG_SLUGS.CERNES_POCHES,
  SKINCARE_PRODUCT_TAG_SLUGS.PROTECTION,
]

export const SKINCARE_PRODUCT_CONCERN_GROUPS: Record<
  SkincareProductConcernGroup,
  readonly SkincareProductTagSlug[]
> = {
  functional: CONCERN_FUNCTIONAL,
  aesthetic: CONCERN_AESTHETIC,
}

const CONCERN: SkincareProductTagSlug[] = [...CONCERN_FUNCTIONAL, ...CONCERN_AESTHETIC]

const SKIN_TYPE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_SECHE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_MIXTE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_GRASSE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_SENSIBLE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_NORMALE,
]

const SKIN_ZONE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_VISAGE,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_CORPS,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_YEUX,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_LEVRES,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_MAINS,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_PIEDS,
]

const PRODUCT_TYPE_V2: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_NETTOYANT,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_TONER,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_MIST,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_SERUM,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_HYDRATANT,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_MASQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_EXFOLIATION,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_SOLAIRE,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_TRAITEMENT,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_PRIMER,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_DEODORANT,
  SKINCARE_PRODUCT_TAG_SLUGS.TYPE_OUTIL,
]

const TEXTURE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_GEL,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_CREME,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_BAUME,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_HUILE,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_LAIT,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_MOUSSE,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_EAU,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_PATCH,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_STICK,
]

const ROUTINE_STEP_V2: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.STEP_NETTOYAGE_1,
  SKINCARE_PRODUCT_TAG_SLUGS.STEP_NETTOYAGE_2,
  SKINCARE_PRODUCT_TAG_SLUGS.STEP_PREPARATION,
  SKINCARE_PRODUCT_TAG_SLUGS.STEP_TRAITEMENT,
  SKINCARE_PRODUCT_TAG_SLUGS.STEP_HYDRATATION,
  SKINCARE_PRODUCT_TAG_SLUGS.STEP_OCCLUSIF,
  SKINCARE_PRODUCT_TAG_SLUGS.STEP_PROTECTION_SOLAIRE,
]

const ROUTINE_MOMENT: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_MATIN,
  SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_SOIR,
  SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_HEBDOMADAIRE,
  SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_USAGE_LOCALISE,
  SKINCARE_PRODUCT_TAG_SLUGS.MOMENT_CRISE,
]

const SKIN_EFFECT: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.OCCLUSIF,
  SKINCARE_PRODUCT_TAG_SLUGS.REPULPANT,
  SKINCARE_PRODUCT_TAG_SLUGS.MATIFIANT,
  SKINCARE_PRODUCT_TAG_SLUGS.PROTECTION_CUTANEE,
  SKINCARE_PRODUCT_TAG_SLUGS.ANTI_OXYDANT,
  SKINCARE_PRODUCT_TAG_SLUGS.APAISANT,
  SKINCARE_PRODUCT_TAG_SLUGS.SEBO_REGULATEUR,
  SKINCARE_PRODUCT_TAG_SLUGS.REPARATEUR,
  SKINCARE_PRODUCT_TAG_SLUGS.PURIFIANT,
  SKINCARE_PRODUCT_TAG_SLUGS.PREBIOTIQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.KERATOLYTIQUE,
]

const SENSATION: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_RICHE,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_LEGERE,
  SKINCARE_PRODUCT_TAG_SLUGS.NON_GRAS,
  SKINCARE_PRODUCT_TAG_SLUGS.FINI_MAT,
  SKINCARE_PRODUCT_TAG_SLUGS.FINI_GLOWY,
  SKINCARE_PRODUCT_TAG_SLUGS.ABSORPTION_RAPIDE,
]

// product_characteristic groups are display-only — DB stores flat slugs with
// type='product_characteristic'. Frontend reads SKINCARE_PRODUCT_CHARACTERISTIC_GROUPS
// to render four sub-sections (tolerance / ethique / technique / comedogenicite).
export const SKINCARE_PRODUCT_CHARACTERISTIC_GROUP_KEYS = [
  'tolerance',
  'ethique',
  'technique',
  'comedogenicite',
] as const
export type SkincareProductCharacteristicGroup =
  (typeof SKINCARE_PRODUCT_CHARACTERISTIC_GROUP_KEYS)[number]

const CHARACTERISTIC_TOLERANCE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.SANS_PARFUM,
  SKINCARE_PRODUCT_TAG_SLUGS.SANS_SAVON,
  SKINCARE_PRODUCT_TAG_SLUGS.HYPOALLERGENIQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.GROSSESSE_COMPATIBLE,
]

const CHARACTERISTIC_ETHIQUE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.BIO_NATUREL,
  SKINCARE_PRODUCT_TAG_SLUGS.VEGAN,
  SKINCARE_PRODUCT_TAG_SLUGS.CRUELTY_FREE,
]

const CHARACTERISTIC_TECHNIQUE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.FILTRES_MINERAUX,
  SKINCARE_PRODUCT_TAG_SLUGS.FILTRES_CHIMIQUES,
  SKINCARE_PRODUCT_TAG_SLUGS.PIGMENTS_VERTS,
]

const CHARACTERISTIC_COMEDOGENICITE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.NON_COMEDOGENE,
  SKINCARE_PRODUCT_TAG_SLUGS.COMEDOGENE,
]

export const SKINCARE_PRODUCT_CHARACTERISTIC_GROUPS: Record<
  SkincareProductCharacteristicGroup,
  readonly SkincareProductTagSlug[]
> = {
  tolerance: CHARACTERISTIC_TOLERANCE,
  ethique: CHARACTERISTIC_ETHIQUE,
  technique: CHARACTERISTIC_TECHNIQUE,
  comedogenicite: CHARACTERISTIC_COMEDOGENICITE,
}

const PRODUCT_CHARACTERISTIC: SkincareProductTagSlug[] = [
  ...CHARACTERISTIC_TOLERANCE,
  ...CHARACTERISTIC_ETHIQUE,
  ...CHARACTERISTIC_TECHNIQUE,
  ...CHARACTERISTIC_COMEDOGENICITE,
]

const ACTIF_CLASS: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.RETINOIDS,
  SKINCARE_PRODUCT_TAG_SLUGS.RETINOL_ALTERNATIVES,
  SKINCARE_PRODUCT_TAG_SLUGS.VITAMIN_C,
  SKINCARE_PRODUCT_TAG_SLUGS.VITAMIN_E,
  SKINCARE_PRODUCT_TAG_SLUGS.NIACINAMIDE,
  SKINCARE_PRODUCT_TAG_SLUGS.AHA,
  SKINCARE_PRODUCT_TAG_SLUGS.BHA,
  SKINCARE_PRODUCT_TAG_SLUGS.PHA,
  SKINCARE_PRODUCT_TAG_SLUGS.ENZYMES_EXFOLIANTS,
  SKINCARE_PRODUCT_TAG_SLUGS.CERAMIDES,
  SKINCARE_PRODUCT_TAG_SLUGS.HYALURONIC_ACID,
  SKINCARE_PRODUCT_TAG_SLUGS.PEPTIDES,
  SKINCARE_PRODUCT_TAG_SLUGS.POLYPHENOLS,
  SKINCARE_PRODUCT_TAG_SLUGS.CENTELLA,
  SKINCARE_PRODUCT_TAG_SLUGS.TYROSINASE_INHIBITORS,
  SKINCARE_PRODUCT_TAG_SLUGS.AZELAIC_ACID,
]

export const SKINCARE_PRODUCT_TAG_TAXONOMY = buildTagTaxonomy<
  SkincareProductTagSlug,
  SkincareProductTagCategory
>(SKINCARE_PRODUCT_TAG_LABELS, {
  concern: CONCERN,
  skin_type: SKIN_TYPE,
  skin_zone: SKIN_ZONE,
  product_type_v2: PRODUCT_TYPE_V2,
  texture: TEXTURE,
  routine_step_v2: ROUTINE_STEP_V2,
  routine_moment: ROUTINE_MOMENT,
  skin_effect: SKIN_EFFECT,
  sensation: SENSATION,
  product_characteristic: PRODUCT_CHARACTERISTIC,
  actif_class: ACTIF_CLASS,
})
