import { SKINCARE_PRODUCT_TAG_SLUGS, type SkincareProductTagSlug } from './tag-slugs'

export const SKINCARE_PRODUCT_TAG_CATEGORIES = [
  'concern',
  'skin_type',
  'skin_zone',
  'product_type',
  'routine_step',
  'skin_effect',
  'product_label',
  'shared_label',
] as const

export type SkincareProductTagCategory = (typeof SKINCARE_PRODUCT_TAG_CATEGORIES)[number]

export interface SkincareProductTagMeta {
  category: SkincareProductTagCategory
}

const CONCERN: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.ANTI_ROUGEURS,
  SKINCARE_PRODUCT_TAG_SLUGS.ROSACEE,
  SKINCARE_PRODUCT_TAG_SLUGS.COUPEROSE,
  SKINCARE_PRODUCT_TAG_SLUGS.FLUSHS,
  SKINCARE_PRODUCT_TAG_SLUGS.BARRIERE_CUTANEE,
  SKINCARE_PRODUCT_TAG_SLUGS.ANTI_TACHES,
  SKINCARE_PRODUCT_TAG_SLUGS.ANTI_ACNE,
  SKINCARE_PRODUCT_TAG_SLUGS.ANTI_AGE,
  SKINCARE_PRODUCT_TAG_SLUGS.HYPERPIGMENTATION,
  SKINCARE_PRODUCT_TAG_SLUGS.DESHYDRATATION,
  SKINCARE_PRODUCT_TAG_SLUGS.PORES_DILATES,
  SKINCARE_PRODUCT_TAG_SLUGS.CERNES_POCHES,
  SKINCARE_PRODUCT_TAG_SLUGS.BRILLANCE,
  SKINCARE_PRODUCT_TAG_SLUGS.ECLAT,
  SKINCARE_PRODUCT_TAG_SLUGS.POST_ACNE,
  SKINCARE_PRODUCT_TAG_SLUGS.CICATRISATION,
  SKINCARE_PRODUCT_TAG_SLUGS.MICROBIOME,
  SKINCARE_PRODUCT_TAG_SLUGS.PHOTO_VIEILLISSEMENT,
  SKINCARE_PRODUCT_TAG_SLUGS.TEINT_TERNE,
  SKINCARE_PRODUCT_TAG_SLUGS.LUMIERE_BLEUE,
  SKINCARE_PRODUCT_TAG_SLUGS.POLLUTION,
  SKINCARE_PRODUCT_TAG_SLUGS.ECZEMA,
  SKINCARE_PRODUCT_TAG_SLUGS.GRAIN_PEAU,
  SKINCARE_PRODUCT_TAG_SLUGS.KERATOSE_PILAIRE,
  SKINCARE_PRODUCT_TAG_SLUGS.PHOTO_PROTECTION,
  SKINCARE_PRODUCT_TAG_SLUGS.BARRIERE_CUTANEE_ALTEREE,
]

const SKIN_TYPE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_SECHE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_MIXTE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_GRASSE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_REACTIVE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_SENSIBLE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_NORMALE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_ATOPIQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_RUGUEUSE,
  SKINCARE_PRODUCT_TAG_SLUGS.PEAU_TOUS_TYPES,
]

const SKIN_ZONE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_VISAGE,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_CORPS,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_YEUX,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_LEVRES,
  SKINCARE_PRODUCT_TAG_SLUGS.ZONE_MAINS,
]

const PRODUCT_TYPE: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.BAUME_DEMAQUILLANT,
  SKINCARE_PRODUCT_TAG_SLUGS.HUILE_DEMAQUILLANTE,
  SKINCARE_PRODUCT_TAG_SLUGS.HUILE_NETTOYANTE,
  SKINCARE_PRODUCT_TAG_SLUGS.GEL_NETTOYANT,
  SKINCARE_PRODUCT_TAG_SLUGS.MOUSSE_NETTOYANTE,
  SKINCARE_PRODUCT_TAG_SLUGS.LAIT_NETTOYANT,
  SKINCARE_PRODUCT_TAG_SLUGS.CREME_NETTOYANTE,
  SKINCARE_PRODUCT_TAG_SLUGS.EAU_MICELLAIRE,
  SKINCARE_PRODUCT_TAG_SLUGS.TONIQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.ESSENCE,
  SKINCARE_PRODUCT_TAG_SLUGS.LOTION,
  SKINCARE_PRODUCT_TAG_SLUGS.BRUME,
  SKINCARE_PRODUCT_TAG_SLUGS.PRIMER,
  SKINCARE_PRODUCT_TAG_SLUGS.SERUM,
  SKINCARE_PRODUCT_TAG_SLUGS.AMPOULE,
  SKINCARE_PRODUCT_TAG_SLUGS.HUILE_VISAGE,
  SKINCARE_PRODUCT_TAG_SLUGS.SPOT_TREATMENT,
  SKINCARE_PRODUCT_TAG_SLUGS.CREME_HYDRATANTE,
  SKINCARE_PRODUCT_TAG_SLUGS.GEL_CREME,
  SKINCARE_PRODUCT_TAG_SLUGS.CREME_DE_NUIT,
  SKINCARE_PRODUCT_TAG_SLUGS.BAUME,
  SKINCARE_PRODUCT_TAG_SLUGS.SLEEPING_MASK,
  SKINCARE_PRODUCT_TAG_SLUGS.CONTOUR_YEUX,
  SKINCARE_PRODUCT_TAG_SLUGS.SOIN_LEVRES,
  SKINCARE_PRODUCT_TAG_SLUGS.EXFOLIANT_CHIMIQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.EXFOLIANT_PHYSIQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.MASQUE_ARGILE,
  SKINCARE_PRODUCT_TAG_SLUGS.MASQUE_TISSU,
  SKINCARE_PRODUCT_TAG_SLUGS.MASQUE_HYDRATANT,
  SKINCARE_PRODUCT_TAG_SLUGS.CREME_SOLAIRE,
  SKINCARE_PRODUCT_TAG_SLUGS.CREME_SOLAIRE_TEINTEE,
  SKINCARE_PRODUCT_TAG_SLUGS.APRES_SOLEIL,
  SKINCARE_PRODUCT_TAG_SLUGS.AUTO_BRONZANT,
  SKINCARE_PRODUCT_TAG_SLUGS.LAIT_CORPS,
  SKINCARE_PRODUCT_TAG_SLUGS.CREME_CORPS,
  SKINCARE_PRODUCT_TAG_SLUGS.CREME_MAINS,
  SKINCARE_PRODUCT_TAG_SLUGS.HUILE_CORPS,
  SKINCARE_PRODUCT_TAG_SLUGS.GOMMAGE_CORPS,
  SKINCARE_PRODUCT_TAG_SLUGS.NETTOYANT_CORPS,
  SKINCARE_PRODUCT_TAG_SLUGS.DEODORANT,
  SKINCARE_PRODUCT_TAG_SLUGS.CREME_PIEDS,
  SKINCARE_PRODUCT_TAG_SLUGS.SHAMPOING,
  SKINCARE_PRODUCT_TAG_SLUGS.APRES_SHAMPOING,
  SKINCARE_PRODUCT_TAG_SLUGS.MASQUE_CHEVEUX,
  SKINCARE_PRODUCT_TAG_SLUGS.SERUM_CHEVEUX,
  SKINCARE_PRODUCT_TAG_SLUGS.HUILE_CHEVEUX,
  SKINCARE_PRODUCT_TAG_SLUGS.PRODUIT_COIFFANT,
  SKINCARE_PRODUCT_TAG_SLUGS.PATCH,
  SKINCARE_PRODUCT_TAG_SLUGS.OUTIL_MASSAGE,
]

const ROUTINE_STEP: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.MATIN,
  SKINCARE_PRODUCT_TAG_SLUGS.SOIR,
  SKINCARE_PRODUCT_TAG_SLUGS.NETTOYANT,
  SKINCARE_PRODUCT_TAG_SLUGS.DOUBLE_NETTOYAGE_1,
  SKINCARE_PRODUCT_TAG_SLUGS.DOUBLE_NETTOYAGE_2,
  SKINCARE_PRODUCT_TAG_SLUGS.PREPARATION,
  SKINCARE_PRODUCT_TAG_SLUGS.TRAITEMENT,
  SKINCARE_PRODUCT_TAG_SLUGS.HYDRATATION,
  SKINCARE_PRODUCT_TAG_SLUGS.EMOLLIENCE,
  SKINCARE_PRODUCT_TAG_SLUGS.PROTECTION_SOLAIRE,
  SKINCARE_PRODUCT_TAG_SLUGS.OCCLUSION,
  SKINCARE_PRODUCT_TAG_SLUGS.SOIN_YEUX,
  SKINCARE_PRODUCT_TAG_SLUGS.SOIN_LOCALISE,
  SKINCARE_PRODUCT_TAG_SLUGS.EXFOLIATION,
  SKINCARE_PRODUCT_TAG_SLUGS.MASQUE_HEBDO,
]

const SKIN_EFFECT: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.OCCLUSIF,
  SKINCARE_PRODUCT_TAG_SLUGS.REPULPANT,
  SKINCARE_PRODUCT_TAG_SLUGS.MATIFIANT,
  SKINCARE_PRODUCT_TAG_SLUGS.PROTECTION_CUTANEE,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_RICHE,
  SKINCARE_PRODUCT_TAG_SLUGS.TEXTURE_LEGERE,
  SKINCARE_PRODUCT_TAG_SLUGS.ANTI_OXYDANT,
  SKINCARE_PRODUCT_TAG_SLUGS.APAISANT,
  SKINCARE_PRODUCT_TAG_SLUGS.SEBO_REGULATEUR,
  SKINCARE_PRODUCT_TAG_SLUGS.REPARATEUR,
  SKINCARE_PRODUCT_TAG_SLUGS.PURIFIANT,
  SKINCARE_PRODUCT_TAG_SLUGS.PREBIOTIQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.KERATOLYTIQUE,
]

const PRODUCT_LABEL: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.SANS_PARFUM,
  SKINCARE_PRODUCT_TAG_SLUGS.BIO_NATUREL,
  SKINCARE_PRODUCT_TAG_SLUGS.VEGAN,
  SKINCARE_PRODUCT_TAG_SLUGS.CRUELTY_FREE,
  SKINCARE_PRODUCT_TAG_SLUGS.HYPOALLERGENIQUE,
  SKINCARE_PRODUCT_TAG_SLUGS.PIGMENTS_VERTS,
  SKINCARE_PRODUCT_TAG_SLUGS.SANS_SAVON,
  SKINCARE_PRODUCT_TAG_SLUGS.FILTRES_CHIMIQUES,
  SKINCARE_PRODUCT_TAG_SLUGS.FILTRES_MINERAUX,
  SKINCARE_PRODUCT_TAG_SLUGS.GROSSESSE_COMPATIBLE,
]

const SHARED_LABEL: SkincareProductTagSlug[] = [
  SKINCARE_PRODUCT_TAG_SLUGS.COMEDOGENE,
  SKINCARE_PRODUCT_TAG_SLUGS.NON_COMEDOGENE,
]

type Entry = [SkincareProductTagSlug, SkincareProductTagMeta]

const entries: Entry[] = [
  ...CONCERN.map((s): Entry => [s, { category: 'concern' }]),
  ...SKIN_TYPE.map((s): Entry => [s, { category: 'skin_type' }]),
  ...SKIN_ZONE.map((s): Entry => [s, { category: 'skin_zone' }]),
  ...PRODUCT_TYPE.map((s): Entry => [s, { category: 'product_type' }]),
  ...ROUTINE_STEP.map((s): Entry => [s, { category: 'routine_step' }]),
  ...SKIN_EFFECT.map((s): Entry => [s, { category: 'skin_effect' }]),
  ...PRODUCT_LABEL.map((s): Entry => [s, { category: 'product_label' }]),
  ...SHARED_LABEL.map((s): Entry => [s, { category: 'shared_label' }]),
]

export const SKINCARE_PRODUCT_TAG_TAXONOMY = Object.fromEntries(entries) as Record<
  SkincareProductTagSlug,
  SkincareProductTagMeta
>

export function getSkincareProductTagCategory(
  slug: SkincareProductTagSlug
): SkincareProductTagCategory | undefined {
  return SKINCARE_PRODUCT_TAG_TAXONOMY[slug]?.category
}
