import { SUPPLEMENT_INGREDIENT_TAG_SLUGS, type SupplementIngredientTagSlug } from './tag-slugs'

export const SUPPLEMENT_INGREDIENT_TAG_CATEGORIES = [
  'goal',
  'moment',
  'restriction',
  'ingredient_attribute',
] as const

export type SupplementIngredientTagCategory = (typeof SUPPLEMENT_INGREDIENT_TAG_CATEGORIES)[number]

export interface SupplementIngredientTagMeta {
  category: SupplementIngredientTagCategory
}

const GOAL: SupplementIngredientTagSlug[] = [
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.SOMMEIL,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.ENERGIE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.COGNITION,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.MEMOIRE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.FOCUS,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.IMMUNITE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.LONGEVITE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.STRESS,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.ANXIETE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.SPORT_PERFORMANCE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.SPORT_RECUPERATION,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.ARTICULATIONS,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.DIGESTION,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.CARDIOVASCULAIRE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.HORMONAL,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.OS,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.VISION,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.DETOX,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.PEAU_ORALE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.CHEVEUX_ORALE,
]

const MOMENT: SupplementIngredientTagSlug[] = [
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.MATIN,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.SOIR,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.AVEC_REPAS,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.A_JEUN,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.PRE_ENTRAINEMENT,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.POST_ENTRAINEMENT,
]

const RESTRICTION: SupplementIngredientTagSlug[] = [
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.GROSSESSE_INCOMPATIBLE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.ALLAITEMENT_INCOMPATIBLE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.ENFANT_NON_ADAPTE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.INTERACTION_ANTICOAGULANTS,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.INSUFFISANCE_HEPATIQUE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.INSUFFISANCE_RENALE,
]

const INGREDIENT_ATTRIBUTE: SupplementIngredientTagSlug[] = [
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.ANTIOXYDANT,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.ADAPTOGENE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.NOOTROPE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.ANTI_INFLAMMATOIRE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.IMMUNO_MODULATEUR,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.PRECURSEUR_NEUROTRANSMETTEUR,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.DONNEUR_METHYLE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.COFACTEUR_ENZYMATIQUE,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.STIMULANT,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS.CALMANT,
]

type Entry = [SupplementIngredientTagSlug, SupplementIngredientTagMeta]

const entries: Entry[] = [
  ...GOAL.map((s): Entry => [s, { category: 'goal' }]),
  ...MOMENT.map((s): Entry => [s, { category: 'moment' }]),
  ...RESTRICTION.map((s): Entry => [s, { category: 'restriction' }]),
  ...INGREDIENT_ATTRIBUTE.map((s): Entry => [s, { category: 'ingredient_attribute' }]),
]

export const SUPPLEMENT_INGREDIENT_TAG_TAXONOMY = Object.fromEntries(entries) as Record<
  SupplementIngredientTagSlug,
  SupplementIngredientTagMeta
>

export function getSupplementIngredientTagCategory(
  slug: SupplementIngredientTagSlug
): SupplementIngredientTagCategory | undefined {
  return SUPPLEMENT_INGREDIENT_TAG_TAXONOMY[slug]?.category
}
