/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UUsernameRouteImport } from './routes/u/$username'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as IngredientsSlugRouteImport } from './routes/ingredients/$slug'
import { Route as AuthVerifyPendingRouteImport } from './routes/auth/verify-pending'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthBannedRouteImport } from './routes/auth/banned'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSuggestedEditsRouteImport } from './routes/admin/suggested-edits'
import { Route as AdminSecurityEventsRouteImport } from './routes/admin/security-events'
import { Route as AdminRoleRequestsRouteImport } from './routes/admin/role-requests'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as ProductsSlugIndexRouteImport } from './routes/products/$slug/index'
import { Route as IngredientsSlugIndexRouteImport } from './routes/ingredients/$slug/index'
import { Route as BlogCategoryIndexRouteImport } from './routes/blog/$category/index'
import { Route as AuthenticatedCollectionIndexRouteImport } from './routes/_authenticated/collection.index'
import { Route as ProductsSlugEditRouteImport } from './routes/products/$slug_/edit'
import { Route as IngredientsSlugEditRouteImport } from './routes/ingredients/$slug_/edit'
import { Route as BlogAdminNewRouteImport } from './routes/blog/admin/new'
import { Route as BlogCategorySlugRouteImport } from './routes/blog/$category/$slug'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users_.$userId'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedIngredientsNewRouteImport } from './routes/_authenticated/ingredients/new'
import { Route as AuthenticatedCollectionMotifsRouteImport } from './routes/_authenticated/collection.motifs'
import { Route as AuthenticatedCollectionAchatsRouteImport } from './routes/_authenticated/collection.achats'
import { Route as ProductsSlugDiscussionsIndexRouteImport } from './routes/products/$slug/discussions/index'
import { Route as IngredientsSlugDiscussionsIndexRouteImport } from './routes/ingredients/$slug/discussions/index'
import { Route as AuthenticatedProductsCompareIndexRouteImport } from './routes/_authenticated/products/compare/index'
import { Route as ProductsSlugDiscussionsThreadIdRouteImport } from './routes/products/$slug/discussions/$threadId'
import { Route as IngredientsSlugDiscussionsThreadIdRouteImport } from './routes/ingredients/$slug/discussions/$threadId'
import { Route as BlogAdminEditSlugRouteImport } from './routes/blog/admin/edit/$slug'
import { Route as AuthenticatedProductsCompareNewRouteImport } from './routes/_authenticated/products/compare/new'
import { Route as AuthenticatedProductsCompareIdRouteImport } from './routes/_authenticated/products/compare/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsSlugRoute = IngredientsSlugRouteImport.update({
  id: '/ingredients/$slug',
  path: '/ingredients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyPendingRoute = AuthVerifyPendingRouteImport.update({
  id: '/auth/verify-pending',
  path: '/auth/verify-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBannedRoute = AuthBannedRouteImport.update({
  id: '/auth/banned',
  path: '/auth/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSuggestedEditsRoute = AdminSuggestedEditsRouteImport.update({
  id: '/suggested-edits',
  path: '/suggested-edits',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityEventsRoute = AdminSecurityEventsRouteImport.update({
  id: '/security-events',
  path: '/security-events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRoleRequestsRoute = AdminRoleRequestsRouteImport.update({
  id: '/role-requests',
  path: '/role-requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProductsSlugIndexRoute = ProductsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const IngredientsSlugIndexRoute = IngredientsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IngredientsSlugRoute,
} as any)
const BlogCategoryIndexRoute = BlogCategoryIndexRouteImport.update({
  id: '/blog/$category/',
  path: '/blog/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCollectionIndexRoute =
  AuthenticatedCollectionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCollectionRoute,
  } as any)
const ProductsSlugEditRoute = ProductsSlugEditRouteImport.update({
  id: '/products/$slug_/edit',
  path: '/products/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsSlugEditRoute = IngredientsSlugEditRouteImport.update({
  id: '/ingredients/$slug_/edit',
  path: '/ingredients/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminNewRoute = BlogAdminNewRouteImport.update({
  id: '/blog/admin/new',
  path: '/blog/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategorySlugRoute = BlogCategorySlugRouteImport.update({
  id: '/blog/$category/$slug',
  path: '/blog/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIngredientsNewRoute =
  AuthenticatedIngredientsNewRouteImport.update({
    id: '/ingredients/new',
    path: '/ingredients/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionMotifsRoute =
  AuthenticatedCollectionMotifsRouteImport.update({
    id: '/motifs',
    path: '/motifs',
    getParentRoute: () => AuthenticatedCollectionRoute,
  } as any)
const AuthenticatedCollectionAchatsRoute =
  AuthenticatedCollectionAchatsRouteImport.update({
    id: '/achats',
    path: '/achats',
    getParentRoute: () => AuthenticatedCollectionRoute,
  } as any)
const ProductsSlugDiscussionsIndexRoute =
  ProductsSlugDiscussionsIndexRouteImport.update({
    id: '/discussions/',
    path: '/discussions/',
    getParentRoute: () => ProductsSlugRoute,
  } as any)
const IngredientsSlugDiscussionsIndexRoute =
  IngredientsSlugDiscussionsIndexRouteImport.update({
    id: '/discussions/',
    path: '/discussions/',
    getParentRoute: () => IngredientsSlugRoute,
  } as any)
const AuthenticatedProductsCompareIndexRoute =
  AuthenticatedProductsCompareIndexRouteImport.update({
    id: '/products/compare/',
    path: '/products/compare/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ProductsSlugDiscussionsThreadIdRoute =
  ProductsSlugDiscussionsThreadIdRouteImport.update({
    id: '/discussions/$threadId',
    path: '/discussions/$threadId',
    getParentRoute: () => ProductsSlugRoute,
  } as any)
const IngredientsSlugDiscussionsThreadIdRoute =
  IngredientsSlugDiscussionsThreadIdRouteImport.update({
    id: '/discussions/$threadId',
    path: '/discussions/$threadId',
    getParentRoute: () => IngredientsSlugRoute,
  } as any)
const BlogAdminEditSlugRoute = BlogAdminEditSlugRouteImport.update({
  id: '/blog/admin/edit/$slug',
  path: '/blog/admin/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProductsCompareNewRoute =
  AuthenticatedProductsCompareNewRouteImport.update({
    id: '/products/compare/new',
    path: '/products/compare/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsCompareIdRoute =
  AuthenticatedProductsCompareIdRouteImport.update({
    id: '/products/compare/$id',
    path: '/products/compare/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/collection': typeof AuthenticatedCollectionRouteWithChildren
  '/feed': typeof AuthenticatedFeedRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/role-requests': typeof AdminRoleRequestsRoute
  '/admin/security-events': typeof AdminSecurityEventsRoute
  '/admin/suggested-edits': typeof AdminSuggestedEditsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
  '/ingredients/$slug': typeof IngredientsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/collection/achats': typeof AuthenticatedCollectionAchatsRoute
  '/collection/motifs': typeof AuthenticatedCollectionMotifsRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/admin/new': typeof BlogAdminNewRoute
  '/ingredients/$slug/edit': typeof IngredientsSlugEditRoute
  '/products/$slug/edit': typeof ProductsSlugEditRoute
  '/collection/': typeof AuthenticatedCollectionIndexRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
  '/ingredients/$slug/': typeof IngredientsSlugIndexRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
  '/products/compare/$id': typeof AuthenticatedProductsCompareIdRoute
  '/products/compare/new': typeof AuthenticatedProductsCompareNewRoute
  '/blog/admin/edit/$slug': typeof BlogAdminEditSlugRoute
  '/ingredients/$slug/discussions/$threadId': typeof IngredientsSlugDiscussionsThreadIdRoute
  '/products/$slug/discussions/$threadId': typeof ProductsSlugDiscussionsThreadIdRoute
  '/products/compare/': typeof AuthenticatedProductsCompareIndexRoute
  '/ingredients/$slug/discussions/': typeof IngredientsSlugDiscussionsIndexRoute
  '/products/$slug/discussions/': typeof ProductsSlugDiscussionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/role-requests': typeof AdminRoleRequestsRoute
  '/admin/security-events': typeof AdminSecurityEventsRoute
  '/admin/suggested-edits': typeof AdminSuggestedEditsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/collection/achats': typeof AuthenticatedCollectionAchatsRoute
  '/collection/motifs': typeof AuthenticatedCollectionMotifsRoute
  '/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/admin/new': typeof BlogAdminNewRoute
  '/ingredients/$slug/edit': typeof IngredientsSlugEditRoute
  '/products/$slug/edit': typeof ProductsSlugEditRoute
  '/collection': typeof AuthenticatedCollectionIndexRoute
  '/blog/$category': typeof BlogCategoryIndexRoute
  '/ingredients/$slug': typeof IngredientsSlugIndexRoute
  '/products/$slug': typeof ProductsSlugIndexRoute
  '/products/compare/$id': typeof AuthenticatedProductsCompareIdRoute
  '/products/compare/new': typeof AuthenticatedProductsCompareNewRoute
  '/blog/admin/edit/$slug': typeof BlogAdminEditSlugRoute
  '/ingredients/$slug/discussions/$threadId': typeof IngredientsSlugDiscussionsThreadIdRoute
  '/products/$slug/discussions/$threadId': typeof ProductsSlugDiscussionsThreadIdRoute
  '/products/compare': typeof AuthenticatedProductsCompareIndexRoute
  '/ingredients/$slug/discussions': typeof IngredientsSlugDiscussionsIndexRoute
  '/products/$slug/discussions': typeof ProductsSlugDiscussionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRouteWithChildren
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/role-requests': typeof AdminRoleRequestsRoute
  '/admin/security-events': typeof AdminSecurityEventsRoute
  '/admin/suggested-edits': typeof AdminSuggestedEditsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/auth/verify-pending': typeof AuthVerifyPendingRoute
  '/ingredients/$slug': typeof IngredientsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/ingredients/': typeof IngredientsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/collection/achats': typeof AuthenticatedCollectionAchatsRoute
  '/_authenticated/collection/motifs': typeof AuthenticatedCollectionMotifsRoute
  '/_authenticated/ingredients/new': typeof AuthenticatedIngredientsNewRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/admin/users_/$userId': typeof AdminUsersUserIdRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/blog/$category/$slug': typeof BlogCategorySlugRoute
  '/blog/admin/new': typeof BlogAdminNewRoute
  '/ingredients/$slug_/edit': typeof IngredientsSlugEditRoute
  '/products/$slug_/edit': typeof ProductsSlugEditRoute
  '/_authenticated/collection/': typeof AuthenticatedCollectionIndexRoute
  '/blog/$category/': typeof BlogCategoryIndexRoute
  '/ingredients/$slug/': typeof IngredientsSlugIndexRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
  '/_authenticated/products/compare/$id': typeof AuthenticatedProductsCompareIdRoute
  '/_authenticated/products/compare/new': typeof AuthenticatedProductsCompareNewRoute
  '/blog/admin/edit/$slug': typeof BlogAdminEditSlugRoute
  '/ingredients/$slug/discussions/$threadId': typeof IngredientsSlugDiscussionsThreadIdRoute
  '/products/$slug/discussions/$threadId': typeof ProductsSlugDiscussionsThreadIdRoute
  '/_authenticated/products/compare/': typeof AuthenticatedProductsCompareIndexRoute
  '/ingredients/$slug/discussions/': typeof IngredientsSlugDiscussionsIndexRoute
  '/products/$slug/discussions/': typeof ProductsSlugDiscussionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/collection'
    | '/feed'
    | '/profile'
    | '/submissions'
    | '/admin/catalog'
    | '/admin/reports'
    | '/admin/role-requests'
    | '/admin/security-events'
    | '/admin/suggested-edits'
    | '/admin/users'
    | '/auth/banned'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/auth/verify-pending'
    | '/ingredients/$slug'
    | '/products/$slug'
    | '/u/$username'
    | '/admin/'
    | '/blog/'
    | '/ingredients/'
    | '/products/'
    | '/collection/achats'
    | '/collection/motifs'
    | '/ingredients/new'
    | '/products/new'
    | '/admin/users/$userId'
    | '/auth/google/callback'
    | '/blog/$category/$slug'
    | '/blog/admin/new'
    | '/ingredients/$slug/edit'
    | '/products/$slug/edit'
    | '/collection/'
    | '/blog/$category/'
    | '/ingredients/$slug/'
    | '/products/$slug/'
    | '/products/compare/$id'
    | '/products/compare/new'
    | '/blog/admin/edit/$slug'
    | '/ingredients/$slug/discussions/$threadId'
    | '/products/$slug/discussions/$threadId'
    | '/products/compare/'
    | '/ingredients/$slug/discussions/'
    | '/products/$slug/discussions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/feed'
    | '/profile'
    | '/submissions'
    | '/admin/catalog'
    | '/admin/reports'
    | '/admin/role-requests'
    | '/admin/security-events'
    | '/admin/suggested-edits'
    | '/admin/users'
    | '/auth/banned'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/auth/verify-pending'
    | '/u/$username'
    | '/admin'
    | '/blog'
    | '/ingredients'
    | '/products'
    | '/collection/achats'
    | '/collection/motifs'
    | '/ingredients/new'
    | '/products/new'
    | '/admin/users/$userId'
    | '/auth/google/callback'
    | '/blog/$category/$slug'
    | '/blog/admin/new'
    | '/ingredients/$slug/edit'
    | '/products/$slug/edit'
    | '/collection'
    | '/blog/$category'
    | '/ingredients/$slug'
    | '/products/$slug'
    | '/products/compare/$id'
    | '/products/compare/new'
    | '/blog/admin/edit/$slug'
    | '/ingredients/$slug/discussions/$threadId'
    | '/products/$slug/discussions/$threadId'
    | '/products/compare'
    | '/ingredients/$slug/discussions'
    | '/products/$slug/discussions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/_authenticated/collection'
    | '/_authenticated/feed'
    | '/_authenticated/profile'
    | '/_authenticated/submissions'
    | '/admin/catalog'
    | '/admin/reports'
    | '/admin/role-requests'
    | '/admin/security-events'
    | '/admin/suggested-edits'
    | '/admin/users'
    | '/auth/banned'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/auth/verify-pending'
    | '/ingredients/$slug'
    | '/products/$slug'
    | '/u/$username'
    | '/admin/'
    | '/blog/'
    | '/ingredients/'
    | '/products/'
    | '/_authenticated/collection/achats'
    | '/_authenticated/collection/motifs'
    | '/_authenticated/ingredients/new'
    | '/_authenticated/products/new'
    | '/admin/users_/$userId'
    | '/auth/google/callback'
    | '/blog/$category/$slug'
    | '/blog/admin/new'
    | '/ingredients/$slug_/edit'
    | '/products/$slug_/edit'
    | '/_authenticated/collection/'
    | '/blog/$category/'
    | '/ingredients/$slug/'
    | '/products/$slug/'
    | '/_authenticated/products/compare/$id'
    | '/_authenticated/products/compare/new'
    | '/blog/admin/edit/$slug'
    | '/ingredients/$slug/discussions/$threadId'
    | '/products/$slug/discussions/$threadId'
    | '/_authenticated/products/compare/'
    | '/ingredients/$slug/discussions/'
    | '/products/$slug/discussions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  AuthBannedRoute: typeof AuthBannedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthVerifyPendingRoute: typeof AuthVerifyPendingRoute
  IngredientsSlugRoute: typeof IngredientsSlugRouteWithChildren
  ProductsSlugRoute: typeof ProductsSlugRouteWithChildren
  UUsernameRoute: typeof UUsernameRoute
  BlogIndexRoute: typeof BlogIndexRoute
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  BlogCategorySlugRoute: typeof BlogCategorySlugRoute
  BlogAdminNewRoute: typeof BlogAdminNewRoute
  IngredientsSlugEditRoute: typeof IngredientsSlugEditRoute
  ProductsSlugEditRoute: typeof ProductsSlugEditRoute
  BlogCategoryIndexRoute: typeof BlogCategoryIndexRoute
  BlogAdminEditSlugRoute: typeof BlogAdminEditSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$slug': {
      id: '/ingredients/$slug'
      path: '/ingredients/$slug'
      fullPath: '/ingredients/$slug'
      preLoaderRoute: typeof IngredientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-pending': {
      id: '/auth/verify-pending'
      path: '/auth/verify-pending'
      fullPath: '/auth/verify-pending'
      preLoaderRoute: typeof AuthVerifyPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/banned': {
      id: '/auth/banned'
      path: '/auth/banned'
      fullPath: '/auth/banned'
      preLoaderRoute: typeof AuthBannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/suggested-edits': {
      id: '/admin/suggested-edits'
      path: '/suggested-edits'
      fullPath: '/admin/suggested-edits'
      preLoaderRoute: typeof AdminSuggestedEditsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security-events': {
      id: '/admin/security-events'
      path: '/security-events'
      fullPath: '/admin/security-events'
      preLoaderRoute: typeof AdminSecurityEventsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/role-requests': {
      id: '/admin/role-requests'
      path: '/role-requests'
      fullPath: '/admin/role-requests'
      preLoaderRoute: typeof AdminRoleRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/products/$slug/': {
      id: '/products/$slug/'
      path: '/'
      fullPath: '/products/$slug/'
      preLoaderRoute: typeof ProductsSlugIndexRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/ingredients/$slug/': {
      id: '/ingredients/$slug/'
      path: '/'
      fullPath: '/ingredients/$slug/'
      preLoaderRoute: typeof IngredientsSlugIndexRouteImport
      parentRoute: typeof IngredientsSlugRoute
    }
    '/blog/$category/': {
      id: '/blog/$category/'
      path: '/blog/$category'
      fullPath: '/blog/$category/'
      preLoaderRoute: typeof BlogCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/collection/': {
      id: '/_authenticated/collection/'
      path: '/'
      fullPath: '/collection/'
      preLoaderRoute: typeof AuthenticatedCollectionIndexRouteImport
      parentRoute: typeof AuthenticatedCollectionRoute
    }
    '/products/$slug_/edit': {
      id: '/products/$slug_/edit'
      path: '/products/$slug/edit'
      fullPath: '/products/$slug/edit'
      preLoaderRoute: typeof ProductsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$slug_/edit': {
      id: '/ingredients/$slug_/edit'
      path: '/ingredients/$slug/edit'
      fullPath: '/ingredients/$slug/edit'
      preLoaderRoute: typeof IngredientsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin/new': {
      id: '/blog/admin/new'
      path: '/blog/admin/new'
      fullPath: '/blog/admin/new'
      preLoaderRoute: typeof BlogAdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$category/$slug': {
      id: '/blog/$category/$slug'
      path: '/blog/$category/$slug'
      fullPath: '/blog/$category/$slug'
      preLoaderRoute: typeof BlogCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users_/$userId': {
      id: '/admin/users_/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ingredients/new': {
      id: '/_authenticated/ingredients/new'
      path: '/ingredients/new'
      fullPath: '/ingredients/new'
      preLoaderRoute: typeof AuthenticatedIngredientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collection/motifs': {
      id: '/_authenticated/collection/motifs'
      path: '/motifs'
      fullPath: '/collection/motifs'
      preLoaderRoute: typeof AuthenticatedCollectionMotifsRouteImport
      parentRoute: typeof AuthenticatedCollectionRoute
    }
    '/_authenticated/collection/achats': {
      id: '/_authenticated/collection/achats'
      path: '/achats'
      fullPath: '/collection/achats'
      preLoaderRoute: typeof AuthenticatedCollectionAchatsRouteImport
      parentRoute: typeof AuthenticatedCollectionRoute
    }
    '/products/$slug/discussions/': {
      id: '/products/$slug/discussions/'
      path: '/discussions'
      fullPath: '/products/$slug/discussions/'
      preLoaderRoute: typeof ProductsSlugDiscussionsIndexRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/ingredients/$slug/discussions/': {
      id: '/ingredients/$slug/discussions/'
      path: '/discussions'
      fullPath: '/ingredients/$slug/discussions/'
      preLoaderRoute: typeof IngredientsSlugDiscussionsIndexRouteImport
      parentRoute: typeof IngredientsSlugRoute
    }
    '/_authenticated/products/compare/': {
      id: '/_authenticated/products/compare/'
      path: '/products/compare'
      fullPath: '/products/compare/'
      preLoaderRoute: typeof AuthenticatedProductsCompareIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/products/$slug/discussions/$threadId': {
      id: '/products/$slug/discussions/$threadId'
      path: '/discussions/$threadId'
      fullPath: '/products/$slug/discussions/$threadId'
      preLoaderRoute: typeof ProductsSlugDiscussionsThreadIdRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/ingredients/$slug/discussions/$threadId': {
      id: '/ingredients/$slug/discussions/$threadId'
      path: '/discussions/$threadId'
      fullPath: '/ingredients/$slug/discussions/$threadId'
      preLoaderRoute: typeof IngredientsSlugDiscussionsThreadIdRouteImport
      parentRoute: typeof IngredientsSlugRoute
    }
    '/blog/admin/edit/$slug': {
      id: '/blog/admin/edit/$slug'
      path: '/blog/admin/edit/$slug'
      fullPath: '/blog/admin/edit/$slug'
      preLoaderRoute: typeof BlogAdminEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/products/compare/new': {
      id: '/_authenticated/products/compare/new'
      path: '/products/compare/new'
      fullPath: '/products/compare/new'
      preLoaderRoute: typeof AuthenticatedProductsCompareNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/compare/$id': {
      id: '/_authenticated/products/compare/$id'
      path: '/products/compare/$id'
      fullPath: '/products/compare/$id'
      preLoaderRoute: typeof AuthenticatedProductsCompareIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCollectionRouteChildren {
  AuthenticatedCollectionAchatsRoute: typeof AuthenticatedCollectionAchatsRoute
  AuthenticatedCollectionMotifsRoute: typeof AuthenticatedCollectionMotifsRoute
  AuthenticatedCollectionIndexRoute: typeof AuthenticatedCollectionIndexRoute
}

const AuthenticatedCollectionRouteChildren: AuthenticatedCollectionRouteChildren =
  {
    AuthenticatedCollectionAchatsRoute: AuthenticatedCollectionAchatsRoute,
    AuthenticatedCollectionMotifsRoute: AuthenticatedCollectionMotifsRoute,
    AuthenticatedCollectionIndexRoute: AuthenticatedCollectionIndexRoute,
  }

const AuthenticatedCollectionRouteWithChildren =
  AuthenticatedCollectionRoute._addFileChildren(
    AuthenticatedCollectionRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRouteWithChildren
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedIngredientsNewRoute: typeof AuthenticatedIngredientsNewRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProductsCompareIdRoute: typeof AuthenticatedProductsCompareIdRoute
  AuthenticatedProductsCompareNewRoute: typeof AuthenticatedProductsCompareNewRoute
  AuthenticatedProductsCompareIndexRoute: typeof AuthenticatedProductsCompareIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCollectionRoute: AuthenticatedCollectionRouteWithChildren,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedIngredientsNewRoute: AuthenticatedIngredientsNewRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProductsCompareIdRoute: AuthenticatedProductsCompareIdRoute,
  AuthenticatedProductsCompareNewRoute: AuthenticatedProductsCompareNewRoute,
  AuthenticatedProductsCompareIndexRoute:
    AuthenticatedProductsCompareIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoleRequestsRoute: typeof AdminRoleRequestsRoute
  AdminSecurityEventsRoute: typeof AdminSecurityEventsRoute
  AdminSuggestedEditsRoute: typeof AdminSuggestedEditsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCatalogRoute: AdminCatalogRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoleRequestsRoute: AdminRoleRequestsRoute,
  AdminSecurityEventsRoute: AdminSecurityEventsRoute,
  AdminSuggestedEditsRoute: AdminSuggestedEditsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface IngredientsSlugRouteChildren {
  IngredientsSlugIndexRoute: typeof IngredientsSlugIndexRoute
  IngredientsSlugDiscussionsThreadIdRoute: typeof IngredientsSlugDiscussionsThreadIdRoute
  IngredientsSlugDiscussionsIndexRoute: typeof IngredientsSlugDiscussionsIndexRoute
}

const IngredientsSlugRouteChildren: IngredientsSlugRouteChildren = {
  IngredientsSlugIndexRoute: IngredientsSlugIndexRoute,
  IngredientsSlugDiscussionsThreadIdRoute:
    IngredientsSlugDiscussionsThreadIdRoute,
  IngredientsSlugDiscussionsIndexRoute: IngredientsSlugDiscussionsIndexRoute,
}

const IngredientsSlugRouteWithChildren = IngredientsSlugRoute._addFileChildren(
  IngredientsSlugRouteChildren,
)

interface ProductsSlugRouteChildren {
  ProductsSlugIndexRoute: typeof ProductsSlugIndexRoute
  ProductsSlugDiscussionsThreadIdRoute: typeof ProductsSlugDiscussionsThreadIdRoute
  ProductsSlugDiscussionsIndexRoute: typeof ProductsSlugDiscussionsIndexRoute
}

const ProductsSlugRouteChildren: ProductsSlugRouteChildren = {
  ProductsSlugIndexRoute: ProductsSlugIndexRoute,
  ProductsSlugDiscussionsThreadIdRoute: ProductsSlugDiscussionsThreadIdRoute,
  ProductsSlugDiscussionsIndexRoute: ProductsSlugDiscussionsIndexRoute,
}

const ProductsSlugRouteWithChildren = ProductsSlugRoute._addFileChildren(
  ProductsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  AuthBannedRoute: AuthBannedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthVerifyPendingRoute: AuthVerifyPendingRoute,
  IngredientsSlugRoute: IngredientsSlugRouteWithChildren,
  ProductsSlugRoute: ProductsSlugRouteWithChildren,
  UUsernameRoute: UUsernameRoute,
  BlogIndexRoute: BlogIndexRoute,
  IngredientsIndexRoute: IngredientsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  BlogCategorySlugRoute: BlogCategorySlugRoute,
  BlogAdminNewRoute: BlogAdminNewRoute,
  IngredientsSlugEditRoute: IngredientsSlugEditRoute,
  ProductsSlugEditRoute: ProductsSlugEditRoute,
  BlogCategoryIndexRoute: BlogCategoryIndexRoute,
  BlogAdminEditSlugRoute: BlogAdminEditSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
