/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as IngredientsIndexRouteImport } from './routes/ingredients/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as IngredientsSlugRouteImport } from './routes/ingredients/$slug'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHabitsRouteImport } from './routes/_authenticated/habits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCollectionRouteImport } from './routes/_authenticated/collection'
import { Route as ProductsSlugIndexRouteImport } from './routes/products/$slug.index'
import { Route as IngredientsSlugIndexRouteImport } from './routes/ingredients/$slug.index'
import { Route as ProductsSlugEditRouteImport } from './routes/products/$slug.edit'
import { Route as IngredientsSlugEditRouteImport } from './routes/ingredients/$slug.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsIndexRoute = IngredientsIndexRouteImport.update({
  id: '/ingredients/',
  path: '/ingredients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsSlugRoute = IngredientsSlugRouteImport.update({
  id: '/ingredients/$slug',
  path: '/ingredients/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHabitsRoute = AuthenticatedHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionRoute = AuthenticatedCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ProductsSlugIndexRoute = ProductsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const IngredientsSlugIndexRoute = IngredientsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IngredientsSlugRoute,
} as any)
const ProductsSlugEditRoute = ProductsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProductsSlugRoute,
} as any)
const IngredientsSlugEditRoute = IngredientsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => IngredientsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/ingredients/$slug': typeof IngredientsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/ingredients/': typeof IngredientsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/ingredients/$slug/edit': typeof IngredientsSlugEditRoute
  '/products/$slug/edit': typeof ProductsSlugEditRoute
  '/ingredients/$slug/': typeof IngredientsSlugIndexRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/collection': typeof AuthenticatedCollectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/habits': typeof AuthenticatedHabitsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/ingredients': typeof IngredientsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/ingredients/$slug/edit': typeof IngredientsSlugEditRoute
  '/products/$slug/edit': typeof ProductsSlugEditRoute
  '/ingredients/$slug': typeof IngredientsSlugIndexRoute
  '/products/$slug': typeof ProductsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/collection': typeof AuthenticatedCollectionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/habits': typeof AuthenticatedHabitsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/ingredients/$slug': typeof IngredientsSlugRouteWithChildren
  '/products/$slug': typeof ProductsSlugRouteWithChildren
  '/ingredients/': typeof IngredientsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/ingredients/$slug/edit': typeof IngredientsSlugEditRoute
  '/products/$slug/edit': typeof ProductsSlugEditRoute
  '/ingredients/$slug/': typeof IngredientsSlugIndexRoute
  '/products/$slug/': typeof ProductsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/collection'
    | '/dashboard'
    | '/habits'
    | '/profile'
    | '/tasks'
    | '/ingredients/$slug'
    | '/products/$slug'
    | '/ingredients/'
    | '/products/'
    | '/ingredients/$slug/edit'
    | '/products/$slug/edit'
    | '/ingredients/$slug/'
    | '/products/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/collection'
    | '/dashboard'
    | '/habits'
    | '/profile'
    | '/tasks'
    | '/ingredients'
    | '/products'
    | '/ingredients/$slug/edit'
    | '/products/$slug/edit'
    | '/ingredients/$slug'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/collection'
    | '/_authenticated/dashboard'
    | '/_authenticated/habits'
    | '/_authenticated/profile'
    | '/_authenticated/tasks'
    | '/ingredients/$slug'
    | '/products/$slug'
    | '/ingredients/'
    | '/products/'
    | '/ingredients/$slug/edit'
    | '/products/$slug/edit'
    | '/ingredients/$slug/'
    | '/products/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  IngredientsSlugRoute: typeof IngredientsSlugRouteWithChildren
  ProductsSlugRoute: typeof ProductsSlugRouteWithChildren
  IngredientsIndexRoute: typeof IngredientsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/': {
      id: '/ingredients/'
      path: '/ingredients'
      fullPath: '/ingredients/'
      preLoaderRoute: typeof IngredientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients/$slug': {
      id: '/ingredients/$slug'
      path: '/ingredients/$slug'
      fullPath: '/ingredients/$slug'
      preLoaderRoute: typeof IngredientsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/habits': {
      id: '/_authenticated/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AuthenticatedHabitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collection': {
      id: '/_authenticated/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof AuthenticatedCollectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/products/$slug/': {
      id: '/products/$slug/'
      path: '/'
      fullPath: '/products/$slug/'
      preLoaderRoute: typeof ProductsSlugIndexRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/ingredients/$slug/': {
      id: '/ingredients/$slug/'
      path: '/'
      fullPath: '/ingredients/$slug/'
      preLoaderRoute: typeof IngredientsSlugIndexRouteImport
      parentRoute: typeof IngredientsSlugRoute
    }
    '/products/$slug/edit': {
      id: '/products/$slug/edit'
      path: '/edit'
      fullPath: '/products/$slug/edit'
      preLoaderRoute: typeof ProductsSlugEditRouteImport
      parentRoute: typeof ProductsSlugRoute
    }
    '/ingredients/$slug/edit': {
      id: '/ingredients/$slug/edit'
      path: '/edit'
      fullPath: '/ingredients/$slug/edit'
      preLoaderRoute: typeof IngredientsSlugEditRouteImport
      parentRoute: typeof IngredientsSlugRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCollectionRoute: typeof AuthenticatedCollectionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHabitsRoute: typeof AuthenticatedHabitsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCollectionRoute: AuthenticatedCollectionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHabitsRoute: AuthenticatedHabitsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface IngredientsSlugRouteChildren {
  IngredientsSlugEditRoute: typeof IngredientsSlugEditRoute
  IngredientsSlugIndexRoute: typeof IngredientsSlugIndexRoute
}

const IngredientsSlugRouteChildren: IngredientsSlugRouteChildren = {
  IngredientsSlugEditRoute: IngredientsSlugEditRoute,
  IngredientsSlugIndexRoute: IngredientsSlugIndexRoute,
}

const IngredientsSlugRouteWithChildren = IngredientsSlugRoute._addFileChildren(
  IngredientsSlugRouteChildren,
)

interface ProductsSlugRouteChildren {
  ProductsSlugEditRoute: typeof ProductsSlugEditRoute
  ProductsSlugIndexRoute: typeof ProductsSlugIndexRoute
}

const ProductsSlugRouteChildren: ProductsSlugRouteChildren = {
  ProductsSlugEditRoute: ProductsSlugEditRoute,
  ProductsSlugIndexRoute: ProductsSlugIndexRoute,
}

const ProductsSlugRouteWithChildren = ProductsSlugRoute._addFileChildren(
  ProductsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  IngredientsSlugRoute: IngredientsSlugRouteWithChildren,
  ProductsSlugRoute: ProductsSlugRouteWithChildren,
  IngredientsIndexRoute: IngredientsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
