import { DENTAL_INGREDIENT_TAG_SLUGS, type DentalIngredientTagSlug } from './tag-slugs'

export const DENTAL_INGREDIENT_TAG_CATEGORIES = [
  'concern',
  'age_group',
  'ingredient_attribute',
  'dental_effect',
] as const

export type DentalIngredientTagCategory = (typeof DENTAL_INGREDIENT_TAG_CATEGORIES)[number]

export interface DentalIngredientTagMeta {
  category: DentalIngredientTagCategory
}

const CONCERN: DentalIngredientTagSlug[] = [
  DENTAL_INGREDIENT_TAG_SLUGS.CARIE,
  DENTAL_INGREDIENT_TAG_SLUGS.SENSIBILITE_DENTINAIRE,
  DENTAL_INGREDIENT_TAG_SLUGS.GENCIVITE,
  DENTAL_INGREDIENT_TAG_SLUGS.PARODONTITE,
  DENTAL_INGREDIENT_TAG_SLUGS.PLAQUE,
  DENTAL_INGREDIENT_TAG_SLUGS.TARTRE,
  DENTAL_INGREDIENT_TAG_SLUGS.TACHES,
  DENTAL_INGREDIENT_TAG_SLUGS.EROSION_ACIDE,
  DENTAL_INGREDIENT_TAG_SLUGS.HALITOSE,
  DENTAL_INGREDIENT_TAG_SLUGS.BRUXISME,
  DENTAL_INGREDIENT_TAG_SLUGS.APHTES,
]

const AGE_GROUP: DentalIngredientTagSlug[] = [
  DENTAL_INGREDIENT_TAG_SLUGS.ADULTE,
  DENTAL_INGREDIENT_TAG_SLUGS.ENFANT,
  DENTAL_INGREDIENT_TAG_SLUGS.SENIOR,
  DENTAL_INGREDIENT_TAG_SLUGS.ORTHODONTIE,
  DENTAL_INGREDIENT_TAG_SLUGS.IMPLANTS,
  DENTAL_INGREDIENT_TAG_SLUGS.DENTS_LAIT,
]

const INGREDIENT_ATTRIBUTE: DentalIngredientTagSlug[] = [
  DENTAL_INGREDIENT_TAG_SLUGS.REMINERALISANT,
  DENTAL_INGREDIENT_TAG_SLUGS.ANTIBACTERIEN,
  DENTAL_INGREDIENT_TAG_SLUGS.ANTI_PLAQUE,
  DENTAL_INGREDIENT_TAG_SLUGS.ANTI_TARTRE,
  DENTAL_INGREDIENT_TAG_SLUGS.ABRASIF_DOUX,
  DENTAL_INGREDIENT_TAG_SLUGS.ABRASIF_FORT,
  DENTAL_INGREDIENT_TAG_SLUGS.BLANCHISSANT,
  DENTAL_INGREDIENT_TAG_SLUGS.NEUTRALISANT_ACIDE,
  DENTAL_INGREDIENT_TAG_SLUGS.FLUORURE,
  DENTAL_INGREDIENT_TAG_SLUGS.DESENSIBILISANT,
  DENTAL_INGREDIENT_TAG_SLUGS.ANTI_INFLAMMATOIRE,
]

const DENTAL_EFFECT: DentalIngredientTagSlug[] = [
  DENTAL_INGREDIENT_TAG_SLUGS.FRAICHEUR,
  DENTAL_INGREDIENT_TAG_SLUGS.BLANCHEUR,
  DENTAL_INGREDIENT_TAG_SLUGS.APAISEMENT_GENCIVES,
  DENTAL_INGREDIENT_TAG_SLUGS.RENFORCEMENT_EMAIL,
  DENTAL_INGREDIENT_TAG_SLUGS.REDUCTION_SENSIBILITE,
]

type Entry = [DentalIngredientTagSlug, DentalIngredientTagMeta]

const entries: Entry[] = [
  ...CONCERN.map((s): Entry => [s, { category: 'concern' }]),
  ...AGE_GROUP.map((s): Entry => [s, { category: 'age_group' }]),
  ...INGREDIENT_ATTRIBUTE.map((s): Entry => [s, { category: 'ingredient_attribute' }]),
  ...DENTAL_EFFECT.map((s): Entry => [s, { category: 'dental_effect' }]),
]

export const DENTAL_INGREDIENT_TAG_TAXONOMY = Object.fromEntries(entries) as Record<
  DentalIngredientTagSlug,
  DentalIngredientTagMeta
>

export function getDentalIngredientTagCategory(
  slug: DentalIngredientTagSlug
): DentalIngredientTagCategory | undefined {
  return DENTAL_INGREDIENT_TAG_TAXONOMY[slug]?.category
}
