// Schemas (runtime validators + inferred types)
export {
  type AuthInput,
  accessTokenPayloadSchema,
  authSchema,
  type ChangePasswordInput,
  changePasswordSchema,
  type Email,
  emailSchema,
  type HashedPassword,
  passwordSchema,
  type RawPassword,
  refreshTokenBodySchema,
  refreshTokenPayloadSchema,
  type SignupFormInput,
  signupSchema,
  verifyEmailBodySchema,
} from './auth'
export {
  type Article,
  type ArticleErrorCode,
  type ArticleListItem,
  type ArticleResponse,
  type ArticleSearchFilters,
  articleErrorMapping,
  articleListItemSchema,
  articleResponseSchema,
  articleSearchSchema,
  BLOG_CATEGORIES,
  BLOG_CATEGORY_LABELS,
  BLOG_CATEGORY_VALUES,
  type BlogCategory,
  type CreateArticleInput,
  createArticleSchema,
  type UpdateArticleInput,
  updateArticleSchema,
} from './blog'
export type { ApiError, ApiResponse, ApiSuccess } from './core'
export {
  baseErrorMapping,
  type CommonErrorCode,
  type ContentfulHttpStatus,
  err,
  errorToStatus,
  type FieldChange,
  type FilterTier,
  fieldChangeSchema,
  HTTP_STATUS,
  type HttpStatus,
  isApiSuccess,
  ok,
  type TagCategoryMeta,
} from './core'
export {
  type CreateReplyInput,
  type CreateThreadInput,
  createReplySchema,
  createThreadSchema,
} from './discussions'
export {
  type AllIngredientTagCategory,
  type CreateIngredientInput,
  createIngredientSchema,
  DENTAL_INGREDIENT_CATEGORIES,
  DENTAL_INGREDIENT_CATEGORY_VALUES,
  DENTAL_INGREDIENT_TAG_CATEGORIES,
  DENTAL_INGREDIENT_TAG_CATEGORY_META,
  DENTAL_INGREDIENT_TAG_SLUGS,
  DENTAL_INGREDIENT_TAG_TAXONOMY,
  type DentalIngredientCategory,
  type DentalIngredientTagCategory,
  type DentalIngredientTagMeta,
  type DentalIngredientTagSlug,
  DOMAIN_INGREDIENT_FILTER_CATEGORIES,
  dentalIngredientFilterCategories,
  getDentalIngredientTagCategory,
  getHaircareIngredientTagCategory,
  getIngredientTagsByCategory,
  getSkincareIngredientTagCategory,
  getSupplementIngredientTagCategory,
  HAIRCARE_INGREDIENT_CATEGORIES,
  HAIRCARE_INGREDIENT_CATEGORY_VALUES,
  HAIRCARE_INGREDIENT_TAG_CATEGORIES,
  HAIRCARE_INGREDIENT_TAG_CATEGORY_META,
  HAIRCARE_INGREDIENT_TAG_SLUGS,
  HAIRCARE_INGREDIENT_TAG_TAXONOMY,
  type HaircareIngredientCategory,
  type HaircareIngredientTagCategory,
  type HaircareIngredientTagMeta,
  type HaircareIngredientTagSlug,
  haircareIngredientFilterCategories,
  INGREDIENT_SORT_VALUES,
  INGREDIENT_TYPE_LABELS,
  INGREDIENT_TYPE_VALUES,
  INGREDIENT_TYPES,
  type Ingredient,
  type IngredientChanges,
  type IngredientEdit,
  type IngredientErrorCode,
  type IngredientFilterOptions,
  type IngredientFilterOptionsTag,
  type IngredientResponse,
  type IngredientSort,
  type IngredientType,
  ingredientChangesSchema,
  ingredientErrorMapping,
  ingredientFilterOptionsSchema,
  ingredientFilterOptionsTagSchema,
  ingredientResponseSchema,
  ingredientSortEnum,
  type ListIngredientsSearchFilters,
  listIngredientsSearchSchema,
  SKINCARE_INGREDIENT_CATEGORIES,
  SKINCARE_INGREDIENT_CATEGORY_VALUES,
  SKINCARE_INGREDIENT_TAG_CATEGORIES,
  SKINCARE_INGREDIENT_TAG_CATEGORY_META,
  SKINCARE_INGREDIENT_TAG_SLUGS,
  SKINCARE_INGREDIENT_TAG_TAXONOMY,
  type SkincareIngredientCategory,
  type SkincareIngredientTagCategory,
  type SkincareIngredientTagMeta,
  type SkincareIngredientTagSlug,
  SUPPLEMENT_CATEGORIES,
  SUPPLEMENT_CATEGORY_VALUES,
  SUPPLEMENT_INGREDIENT_TAG_CATEGORIES,
  SUPPLEMENT_INGREDIENT_TAG_CATEGORY_META,
  SUPPLEMENT_INGREDIENT_TAG_SLUGS,
  SUPPLEMENT_INGREDIENT_TAG_TAXONOMY,
  type SupplementCategory,
  type SupplementIngredientTagCategory,
  type SupplementIngredientTagMeta,
  type SupplementIngredientTagSlug,
  skincareIngredientFilterCategories,
  supplementIngredientFilterCategories,
  type UpdateIngredientInput,
  type UpdateIngredientRouteInput,
  updateIngredientRouteSchema,
  updateIngredientSchema,
} from './ingredients'
export {
  type AllProductTagCategory,
  COMPARISON_MAX_PRODUCTS,
  COMPARISON_MIN_PRODUCTS,
  type ComparisonPriceUnit,
  type ComparisonSummary,
  type ComplementListProductsFilters,
  type CreateComparisonInput,
  type CreateProductInput,
  classifyIngredientSignals,
  complementListProductsQuery,
  createComparisonSchema,
  createProductIngredientSchema,
  createProductSchema,
  DENTAL_PRODUCT_TAG_CATEGORIES,
  DENTAL_PRODUCT_TAG_CATEGORY_META,
  DENTAL_PRODUCT_TAG_SLUGS,
  DENTAL_PRODUCT_TAG_TAXONOMY,
  DERMO_CONFLICTS,
  type DentalListProductsFilters,
  type DentalProductFilterOptions,
  type DentalProductTagCategory,
  type DentalProductTagMeta,
  type DentalProductTagSlug,
  type DermoConflict,
  type DermoConflictSeverity,
  type DermoSignal,
  DOMAIN_PRODUCT_FILTER_CATEGORIES,
  dentalListProductsQuery,
  dentalProductFilterCategories,
  dentalProductFilterOptionsSchema,
  type EnrichedComparison,
  type EnrichedComparisonProduct,
  getProductKindLabel,
  getProductTagCategory,
  getProductTagLabel,
  getProductTagsByCategory,
  getProductUnitLabel,
  HAIRCARE_PRODUCT_TAG_CATEGORIES,
  HAIRCARE_PRODUCT_TAG_CATEGORY_META,
  HAIRCARE_PRODUCT_TAG_SLUGS,
  HAIRCARE_PRODUCT_TAG_TAXONOMY,
  type HaircareListProductsFilters,
  type HaircareProductFilterOptions,
  type HaircareProductTagCategory,
  type HaircareProductTagMeta,
  type HaircareProductTagSlug,
  haircareListProductsQuery,
  haircareProductFilterCategories,
  haircareProductFilterOptionsSchema,
  type ListProductsFilters,
  listProductsQuery,
  type Patent,
  PRODUCT_AMOUNT_UNIT_LABELS,
  PRODUCT_AMOUNT_UNIT_VALUES,
  PRODUCT_AMOUNT_UNITS,
  PRODUCT_CATEGORIES,
  PRODUCT_CATEGORY_LABELS,
  PRODUCT_CATEGORY_TO_DOMAIN_TAB,
  PRODUCT_CATEGORY_VALUES,
  PRODUCT_CONCENTRATION_UNIT_LABELS,
  PRODUCT_CONCENTRATION_UNIT_VALUES,
  PRODUCT_DOMAIN_DB_CATEGORIES,
  PRODUCT_DOMAIN_TAB_META,
  PRODUCT_DOMAIN_TABS,
  PRODUCT_KIND_LABELS,
  PRODUCT_KINDS,
  PRODUCT_SORT_VALUES,
  PRODUCT_TEXTURE_LABELS,
  PRODUCT_TEXTURE_VALUES,
  PRODUCT_TEXTURES,
  PRODUCT_UNIT_LABELS,
  PRODUCT_UNIT_VALUES,
  PRODUCT_UNITS,
  type ProductAmountUnit,
  type ProductCategory,
  type ProductChanges,
  type ProductComparisonErrorCode,
  type ProductConcentrationUnit,
  type ProductDomainTab,
  type ProductErrorCode,
  type ProductIngredientErrorCode,
  type ProductKind,
  type ProductKindsMap,
  type ProductSearchPage,
  type ProductSearchResult,
  type ProductSort,
  type ProductTexture,
  type ProductUnit,
  type ProductUnitsMap,
  productChangesSchema,
  productComparisonErrorMapping,
  productErrorMapping,
  productIngredientErrorMapping,
  productSortEnum,
  productsByIdsQuery,
  SKINCARE_PRODUCT_CHARACTERISTIC_GROUP_KEYS,
  SKINCARE_PRODUCT_CHARACTERISTIC_GROUPS,
  SKINCARE_PRODUCT_CONCERN_GROUP_KEYS,
  SKINCARE_PRODUCT_CONCERN_GROUPS,
  SKINCARE_PRODUCT_TAG_CATEGORIES,
  SKINCARE_PRODUCT_TAG_CATEGORY_META,
  SKINCARE_PRODUCT_TAG_SLUGS,
  SKINCARE_PRODUCT_TAG_TAXONOMY,
  type SkincareListProductsFilters,
  type SkincareProductCharacteristicGroup,
  type SkincareProductConcernGroup,
  type SkincareProductFilterOptions,
  type SkincareProductTagCategory,
  type SkincareProductTagMeta,
  type SkincareProductTagSlug,
  SUPPLEMENT_PRODUCT_TAG_CATEGORIES,
  SUPPLEMENT_PRODUCT_TAG_CATEGORY_META,
  SUPPLEMENT_PRODUCT_TAG_SLUGS,
  SUPPLEMENT_PRODUCT_TAG_TAXONOMY,
  type SupplementProductFilterOptions,
  type SupplementProductTagCategory,
  type SupplementProductTagMeta,
  type SupplementProductTagSlug,
  searchProductsQuery,
  skincareListProductsQuery,
  skincareProductFilterCategories,
  skincareProductFilterOptionsSchema,
  supplementProductFilterCategories,
  supplementProductFilterOptionsSchema,
  type UpdateComparisonInput,
  type UpdateProductInput,
  updateComparisonSchema,
  updateProductSchema,
} from './products'
export {
  BIO_MAX_LENGTH,
  type CriteriaWeights,
  criteriaWeightsSchema,
  type DisplayScale,
  displayScale,
  displayScaleSchema,
  type PrivacySettings,
  type ProfileLink,
  type ProfilePublic,
  type ProfileStats,
  type ProfileUpdateInput,
  profileUpdateSchema,
  SKIN_CONCERNS,
  SKIN_TYPES,
  type SkinConcern,
  type SkinType,
  type UpdatePrivacySettingsInput,
  type UpdateUserPreferencesInput,
  USERNAME_MAX_LENGTH,
  type UserDermoProfile,
  type UserDermoProfileUpdateInput,
  type UserPreferences,
  updatePrivacySettingsSchema,
  updateUserPreferencesSchema,
  userDermoProfileUpdateSchema,
} from './profile'
export {
  type AddPurchaseInput,
  addPurchaseSchema,
  type FinishPurchaseInput,
  finishPurchaseSchema,
  type OpenPurchaseInput,
  openPurchaseSchema,
  type Purchase,
  purchaseSchema,
  type UpdatePurchaseInput,
  updatePurchaseSchema,
} from './purchases'
export {
  addIngredientTagSchema,
  type CreateTagInput,
  createTagSchema,
  type ReplaceIngredientTagsInput,
  type ReplaceProductTagsInput,
  relevanceEnum,
  relevanceValues,
  replaceIngredientTagsSchema,
  replaceProductTagsSchema,
  type UpdateTagInput,
  updateTagSchema,
} from './tags'
export {
  type CreateSubtaskInput,
  type CreateTaskInput,
  createSubtaskSchema,
  createTaskSchema,
  type Subtask,
  subtaskSchema,
  type Task,
  taskSchema,
  type UpdateSubtaskInput,
  type UpdateTaskInput,
  updateSubtaskSchema,
  updateTaskSchema,
} from './tasks'
export {
  type UploadErrorCode,
  type UploadResponse,
  uploadErrorMapping,
  uploadResponseSchema,
} from './uploads'
export {
  type CreateUserProductInput,
  createUserProductSchema,
  type RepurchaseFlag,
  repurchaseFlag,
  repurchaseFlagSchema,
  type UpdateUserProductInput,
  type UpdateUserProductReviewInput,
  type UserProductErrorCode,
  type UserProductStatus,
  updateUserProductReviewSchema,
  updateUserProductSchema,
  userProductErrorMapping,
  userProductStatus,
  userProductStatusSchema,
} from './user-products'

// Types (entity types, error codes, composed types)

export type {
  AccessTokenPayload,
  AuthErrorCode,
  AuthenticatedResult,
  ChangePasswordResult,
  CreateRefreshTokenArgs,
  GoogleCallbackResult,
  LoginErrorCode,
  LoginResult,
  LogoutResult,
  MobileAuthResult,
  RefreshResult,
  RefreshTokenPayload,
  SignupErrorCode,
  SignupResult,
  UserPublic,
} from './auth'
export type {
  DiscussionErrorCode,
  DiscussionReply,
  DiscussionThread,
  DiscussionThreadWithReplies,
} from './discussions'
export type { PurchaseErrorCode } from './purchases'
export type { TagErrorCode } from './tags'
export type { TaskEnergy, TaskErrorCode, TaskStatus } from './tasks'

// Helpers (error mappings, constants, utilities)

export { authErrorMapping } from './auth'
export { discussionErrorMapping } from './discussions'
export { purchaseErrorMapping } from './purchases'
export { tagErrorMapping } from './tags'
export { taskErrorMapping } from './tasks'
